/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2016/12/17  12:15:58                                     */
/**           By : uidp4501                                                 */
/**        Using : NAT_Cfg_Template_Release_A10.xls                         */
/**         From : D:\HVACProject\Geely\FE-5A7A\ATC\01_Application\02_Sources\01_CC\01_APP\NATS*/
/**               (D = )                                                    */
/**************************************************************************************/
 
/******************************************************************************
Module Name : NAT
File Name : NAT_Cfg.h
-------------------------------------------------------------------------------
               C O P Y R I G H T
-------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.   All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 -------------------------------------------------------------------------------
  Name                                                   Company
  ---------------------          ---------------------------------------
 uidp4501                         Desay SV Automotive Co., Ltd
  ---------------------          ---------------------------------------
******************************************************************************/
 
/* Module Define  */
#ifndef NAT_CFG_H
#define NAT_CFG_H

/* System-headerfiles */
#include "General.h"


/******************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/

#define  NAT_nStaticOffsetTblLen    (7U)
#define  NAT_nDynamicOffsetTblLen    (7U)
#define  NAT_nThermalOffsetLen    (5U)
#define  NAT_nRadOffsetTblLen    (13U)
#define  NAT_nSurfTempTblLen    (11U)
#define  NAT_nPCBTempTblLen    (11U)

/*************************** Define Structures Arrary length ************************/

typedef struct NAT_stNatInfo
{
   uint8    u8VariableConst;
   uint8    u8ModuleID;
   uint16   u16ModuleLen;
} NAT_tstNatInfo;

typedef struct NAT_stData
{
   uint16   au16StaticOffsetX [ NAT_nStaticOffsetTblLen ];
   uint16   au16StaticOffsetY [ NAT_nStaticOffsetTblLen ];
   uint16   au16DynamicOffsetX [ NAT_nDynamicOffsetTblLen ];
   uint16   au16DynamicOffsetY [ NAT_nDynamicOffsetTblLen ];
   uint16   au16ThermalOffsetX [ NAT_nThermalOffsetLen ];
   uint16   au16ThermalOffsetY [ NAT_nThermalOffsetLen ];
   uint16   au16RadOffsetX [ NAT_nRadOffsetTblLen ];
   uint16   au16RadOffsetY [ NAT_nRadOffsetTblLen ];
   uint16   au16SurfTempXTbl [ NAT_nSurfTempTblLen ];
   uint16   au16SurfTempYTbl [ NAT_nSurfTempTblLen ];
   uint16   au16PCBTempXTbl [ NAT_nPCBTempTblLen ];
   uint16   au16PCBTempYTbl [ NAT_nPCBTempTblLen ];
} NAT_tstData;

/*************************** Group Structures ************************/
typedef struct NAT_stGroup
{
   NAT_tstNatInfo  stNatInfo;
   NAT_tstData  stData;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} NAT_tstGroup;

/********************** LAYOUT STRUCTURE ****************************/

typedef struct 
{
   NAT_tstGroup  stGroup;
} NAT_tstRomLayout;

extern  const NAT_tstRomLayout NAT_stRomLayout;

/********************* VARIABLE ACCESS MACROS ***************************/
#define   NAT_u8GroupVariableConst                (NAT_stRomLayout.stGroup.stNatInfo.u8VariableConst)
#define   NAT_u8GroupModuleID                     (NAT_stRomLayout.stGroup.stNatInfo.u8ModuleID)
#define   NAT_u16GroupModuleLen                   (NAT_stRomLayout.stGroup.stNatInfo.u16ModuleLen)
#define   NAT_au16GroupStaticOffsetX              (NAT_stRomLayout.stGroup.stData.au16StaticOffsetX)
#define   NAT_au16GroupStaticOffsetY              (NAT_stRomLayout.stGroup.stData.au16StaticOffsetY)
#define   NAT_au16GroupDynamicOffsetX             (NAT_stRomLayout.stGroup.stData.au16DynamicOffsetX)
#define   NAT_au16GroupDynamicOffsetY             (NAT_stRomLayout.stGroup.stData.au16DynamicOffsetY)
#define   NAT_au16GroupThermalOffsetX             (NAT_stRomLayout.stGroup.stData.au16ThermalOffsetX)
#define   NAT_au16GroupThermalOffsetY             (NAT_stRomLayout.stGroup.stData.au16ThermalOffsetY)
#define   NAT_au16GroupRadOffsetX                 (NAT_stRomLayout.stGroup.stData.au16RadOffsetX)
#define   NAT_au16GroupRadOffsetY                 (NAT_stRomLayout.stGroup.stData.au16RadOffsetY)
#define   NAT_au16GroupSurfTempXTbl               (NAT_stRomLayout.stGroup.stData.au16SurfTempXTbl)
#define   NAT_au16GroupSurfTempYTbl               (NAT_stRomLayout.stGroup.stData.au16SurfTempYTbl)
#define   NAT_au16GroupPCBTempXTbl                (NAT_stRomLayout.stGroup.stData.au16PCBTempXTbl)
#define   NAT_au16GroupPCBTempYTbl                (NAT_stRomLayout.stGroup.stData.au16PCBTempYTbl)
#define   NAT_nUseRTE                             (0U)    /*Hct Disbale fog in Warm-up and heating judgment*/
#define   NAT_nUseCCP                             (1U)    /*Hct Enable fog in Warm-up and heating judgment*/
#define   NAT_nSurfSensorMin                      (21U)    /**/
#define   NAT_nSurfSensorMax                      (1000U)    /**/
#define   NAT_nSurfSensorDefaultValue             (400U)    /**/
#define   NAT_nPcbSensorMin                       (21U)    /**/
#define   NAT_nPcbSensorMax                       (1000U)    /**/
#define   NAT_nPcbSensorDefaultValue              (400U)    /**/
#define   NAT_nErrorCountTimeout                  (5U)    /**/
#define   NAT_nFilterParameter                    (4U)    /**/
/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*NAT_Cfg.h
******************************************************************************/
