/************************** DEFAULTS ************************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 2017/10/30  11:26:24                                     */
/**           By : uidp4501                                                 */
/**        Using : SUN_Cfg.xls                                              */
/**         From : D:\HVACProject\Geely\FE-5DB&7DA\ProjectCode\01_APP\SUN\新建文件夹*/
/**               (D = )                                                    */
/****************************************************************************/

/*****************************************************************************
* FILE DECLARATION
*****************************************************************************/

#define SUN_CFG

/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
*****************************************************************************/
#include "SUN.h"


/*****************************************************************************
* MODULE GLOBAL CONFIGURATION CONSTANTS
*
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
*****************************************************************************/




const SUN_tstRomLayout SUN_stRomLayout = {

   {  /*----------------------- Group1 ---------------------------------------*/

      {  /* Info1 */
         0x1U,                                                    /* u8VariableConst */
         0x0U,                                                    /* u8ChipType */
         0xFFU,                                                   /* u8HeaderFillByte1 */
         0xFFU                                                    /* u8HeaderFillByte2 */
      },

      {  /* Data1 */
         { 0x0125U,0x018FU,0x01FAU,0x0264U,0x02CFU,0x0339U,0x03A3U },  /* au16SunSensorValueX */
         { 0x04B0U,0x03E8U,0x0320U,0x0258U,0x0190U,0x00C8U,0x0000U }  /* au16SunSensorValueY */
      },
      0xC1U,                                                      /* u8AddChkSum */
      0x1FU                                                       /* u8XorChkSum */
   },

   {  /*----------------------- Group2 ---------------------------------------*/

      {  /* Info2 */
         0x1U,                                                    /* u8VariableConst */
         0xFFU                                                    /* u8HeaderFillByte1 */
      },

      {  /* Data2 */
         { 0x0000U,0x00C8U,0x0190U,0x0258U,0x0320U,0x04B0U },     /* au16TempOffsetTbl_X */
         { 0x0280U,0x0280U,0x0280U,0x0280U,0x0280U,0x0280U },     /* au16TempOffsetTbl_Y0 */
         { 0x0280U,0x0280U,0x0280U,0x0280U,0x0280U,0x0280U },     /* au16TempOffsetTbl_Y1 */
         { 0x0280U,0x025DU,0x0253U,0x0230U,0x0230U,0x0230U },     /* au16TempOffsetTbl_Y2 */
         { 0x0280U,0x0253U,0x0244U,0x0226U,0x0226U,0x0226U },     /* au16TempOffsetTbl_Y3 */
         { 0x00FAU,0x01C2U,0x028AU,0x02EEU }                      /* au16TempOffsetAmbientTbl */
      },
      0xC3U,                                                      /* u8AddChkSum */
      0x39U                                                       /* u8XorChkSum */
   },

   {  /*----------------------- Group3 ---------------------------------------*/

      {  /* Info3 */
         0x1U,                                                    /* u8VariableConst */
         0xFFU                                                    /* u8HeaderFillByte1 */
      },

      {  /* Data3 */
         { 0x0000U,0x00C8U,0x0190U,0x01F4U,0x0320U,0x04B0U },     /* au16BlowerOffsetTbl_X */
         { 0x03E8U,0x03E8U,0x03E8U,0x03E8U,0x03E8U,0x03E8U },     /* au16BlowerOffsetTbl_Y0 */
         { 0x03E8U,0x03E8U,0x03E8U,0x03E8U,0x03E8U,0x03E8U },     /* au16BlowerOffsetTbl_Y1 */
         { 0x03E8U,0x046AU,0x04B0U,0x05AAU,0x0690U,0x06D6U },     /* au16BlowerOffsetTbl_Y2 */
         { 0x03E8U,0x0532U,0x062CU,0x06D6U,0x073AU,0x0802U },     /* au16BlowerOffsetTbl_Y3 */
         { 0x00FAU,0x01C2U,0x028AU,0x02EEU }                      /* au16BlowerOffsetAmbientTbl */
      },
      0xF4U,                                                      /* u8AddChkSum */
      0x52U                                                       /* u8XorChkSum */
   }
};
