/********************* MODULE STRUCTURE DEFINITIONS *************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 2017/10/30  11:26:23                                     */
/**           By : uidp4501                                                 */
/**        Using : SUN_Cfg.xls                                              */
/**         From : D:\HVACProject\Geely\FE-5DB&7DA\ProjectCode\01_APP\SUN\新建文件夹*/
/**               (D = )                                                    */
/****************************************************************************/
/*****************************************************************************
* FILE DECLARATION
******************************************************************************/
#ifndef SUN_CFG_H
#define SUN_CFG_H
/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
******************************************************************************/
/* System-headerfiles */
#include "General.h"


/*****************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/


#define  SUN_nSunSensorValue_Len    (7U)
#define  SUN_nTempOffsetTbl_Len    (6U)
#define  SUN_nTempAmbientTbl_Len    (4U)
#define  SUN_nBlowerOffsetTbl_Len    (6U)
#define  SUN_nBlowerAmbientTbl_Len    (4U)

/*************************** Define Structures Arrary length ************************/

typedef const struct SUN_stInfo1
{
   const uint8    u8VariableConst;
   const uint8    u8ChipType;
   const uint8    u8HeaderFillByte1;
   const uint8    u8HeaderFillByte2;
} SUN_tstInfo1;

typedef const struct SUN_stData1
{
   const uint16   au16SunSensorValueX [ SUN_nSunSensorValue_Len ];
   const uint16   au16SunSensorValueY [ SUN_nSunSensorValue_Len ];
} SUN_tstData1;

typedef const struct SUN_stInfo2
{
   const uint8    u8VariableConst;
   const uint8    u8HeaderFillByte1;
} SUN_tstInfo2;

typedef const struct SUN_stData2
{
   const uint16   au16TempOffsetTbl_X [ SUN_nTempOffsetTbl_Len ];
   const uint16   au16TempOffsetTbl_Y0 [ SUN_nTempOffsetTbl_Len ];
   const uint16   au16TempOffsetTbl_Y1 [ SUN_nTempOffsetTbl_Len ];
   const uint16   au16TempOffsetTbl_Y2 [ SUN_nTempOffsetTbl_Len ];
   const uint16   au16TempOffsetTbl_Y3 [ SUN_nTempOffsetTbl_Len ];
   const uint16   au16TempOffsetAmbientTbl [ SUN_nTempAmbientTbl_Len ];
} SUN_tstData2;

typedef const struct SUN_stInfo3
{
   const uint8    u8VariableConst;
   const uint8    u8HeaderFillByte1;
} SUN_tstInfo3;

typedef const struct SUN_stData3
{
   const uint16   au16BlowerOffsetTbl_X [ SUN_nBlowerOffsetTbl_Len ];
   const uint16   au16BlowerOffsetTbl_Y0 [ SUN_nBlowerOffsetTbl_Len ];
   const uint16   au16BlowerOffsetTbl_Y1 [ SUN_nBlowerOffsetTbl_Len ];
   const uint16   au16BlowerOffsetTbl_Y2 [ SUN_nBlowerOffsetTbl_Len ];
   const uint16   au16BlowerOffsetTbl_Y3 [ SUN_nBlowerOffsetTbl_Len ];
   const uint16   au16BlowerOffsetAmbientTbl [ SUN_nBlowerAmbientTbl_Len ];
} SUN_tstData3;

/*************************** Group Structures ************************/
typedef const struct SUN_stGroup1
{
   SUN_tstInfo1  stInfo1;
   SUN_tstData1  stData1;
   const uint8  u8AddChkSum;
   const uint8  u8XorChkSum;
} SUN_tstGroup1;

typedef const struct SUN_stGroup2
{
   SUN_tstInfo2  stInfo2;
   SUN_tstData2  stData2;
   const uint8  u8AddChkSum;
   const uint8  u8XorChkSum;
} SUN_tstGroup2;

typedef const struct SUN_stGroup3
{
   SUN_tstInfo3  stInfo3;
   SUN_tstData3  stData3;
   const uint8  u8AddChkSum;
   const uint8  u8XorChkSum;
} SUN_tstGroup3;

/********************** LAYOUT STRUCTURE ****************************/

typedef const struct 
{
   SUN_tstGroup1  stGroup1;
   SUN_tstGroup2  stGroup2;
   SUN_tstGroup3  stGroup3;
} SUN_tstRomLayout;

extern const SUN_tstRomLayout SUN_stRomLayout;

/********************* VARIABLE ACCESS MACROS ***************************/
#define   SUN_u8Group1VariableConst               (SUN_stRomLayout.stGroup1.stInfo1.u8VariableConst)
#define   SUN_u8Group1ChipType                    (SUN_stRomLayout.stGroup1.stInfo1.u8ChipType)
#define   SUN_u8Group1HeaderFillByte1             (SUN_stRomLayout.stGroup1.stInfo1.u8HeaderFillByte1)
#define   SUN_u8Group1HeaderFillByte2             (SUN_stRomLayout.stGroup1.stInfo1.u8HeaderFillByte2)
#define   SUN_au16Group1SunSensorValueX           (SUN_stRomLayout.stGroup1.stData1.au16SunSensorValueX)
#define   SUN_au16Group1SunSensorValueY           (SUN_stRomLayout.stGroup1.stData1.au16SunSensorValueY)
#define   SUN_u8Group2VariableConst               (SUN_stRomLayout.stGroup2.stInfo2.u8VariableConst)
#define   SUN_u8Group2HeaderFillByte1             (SUN_stRomLayout.stGroup2.stInfo2.u8HeaderFillByte1)
#define   SUN_au16Group2TempOffsetTbl_X           (SUN_stRomLayout.stGroup2.stData2.au16TempOffsetTbl_X)
#define   SUN_au16Group2TempOffsetTbl_Y0          (SUN_stRomLayout.stGroup2.stData2.au16TempOffsetTbl_Y0)
#define   SUN_au16Group2TempOffsetTbl_Y1          (SUN_stRomLayout.stGroup2.stData2.au16TempOffsetTbl_Y1)
#define   SUN_au16Group2TempOffsetTbl_Y2          (SUN_stRomLayout.stGroup2.stData2.au16TempOffsetTbl_Y2)
#define   SUN_au16Group2TempOffsetTbl_Y3          (SUN_stRomLayout.stGroup2.stData2.au16TempOffsetTbl_Y3)
#define   SUN_au16Group2TempOffsetAmbientTbl          (SUN_stRomLayout.stGroup2.stData2.au16TempOffsetAmbientTbl)
#define   SUN_u8Group3VariableConst               (SUN_stRomLayout.stGroup3.stInfo3.u8VariableConst)
#define   SUN_u8Group3HeaderFillByte1             (SUN_stRomLayout.stGroup3.stInfo3.u8HeaderFillByte1)
#define   SUN_au16Group3BlowerOffsetTbl_X          (SUN_stRomLayout.stGroup3.stData3.au16BlowerOffsetTbl_X)
#define   SUN_au16Group3BlowerOffsetTbl_Y0          (SUN_stRomLayout.stGroup3.stData3.au16BlowerOffsetTbl_Y0)
#define   SUN_au16Group3BlowerOffsetTbl_Y1          (SUN_stRomLayout.stGroup3.stData3.au16BlowerOffsetTbl_Y1)
#define   SUN_au16Group3BlowerOffsetTbl_Y2          (SUN_stRomLayout.stGroup3.stData3.au16BlowerOffsetTbl_Y2)
#define   SUN_au16Group3BlowerOffsetTbl_Y3          (SUN_stRomLayout.stGroup3.stData3.au16BlowerOffsetTbl_Y3)
#define   SUN_au16Group3BlowerOffsetAmbientTbl          (SUN_stRomLayout.stGroup3.stData3.au16BlowerOffsetAmbientTbl)
#define   SUN_nFastRiseSpeed                      (70U)    /**/
#define   SUN_nFastFallSpeed                      (50U)    /**/
#define   SUN_nSlowRiseSpeed                      (30U)    /**/
#define   SUN_nSlowFallSpeed                      (20U)    /**/
#define   SUN_nReserve1                           (0U)    /**/
/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*SUN_Cfg.h
******************************************************************************/
