/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 23/03/2016  15:28:52                                     */
/**           By : uidp4036                                                 */
/**        Using : Hct_Cfg_Template_Release_A11.xls                         */
/**         From : D:\HVACProject\Geely\Geely FE-3HP\SVN Check Out\03_SW\02_Source Code\01_Development Workspace\01_Project\01_Application\02_Sources\01_CC\01_APP\HCT\Generate*/
/**               (D = )                                                    */
/**************************************************************************************/

/**************************************************************************************
 Module Name : HCT
 File Name : HCT_Cfg.c
--------------------------------------------------------------------------------------
               C O P Y R I G H T
--------------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.    All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 ------------------------------------------------------------------------------------
  Name                                          Company
  -----------------------------          ---------------------------------------
 uidp4036                              Desay SV Automotive Co., Ltd
  -----------------------------          ---------------------------------------
***************************************************************************************/
/*Module Define*/
#define HCT_CFG

/*Header file */
#include "HCT_Cfg.h"

/***************************************************************************************
*MODULE GLOBAL CONFIGURATION CONSTANTS
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
***************************************************************************************/


HCT_tstLayout HCT_stLayout;


 const HCT_tstLayout HCT_stDefaultLayout = {

   {  /*----------------------- Group1 ---------------------------------------*/

      {  /* HctInfo */
         0x0U,                                                    /* u8VariableConst */
         0x0U,                                                    /* u8ChipType */
         0xFFU,                                                   /* u8HeaderFillByte1 */
         0xFFU                                                    /* u8HeaderFillByte2 */
      },

      {  /* HctData */
         { 0x0014U,0x003CU,0x0064U },                             /* au16BumpSpeed_Tbl */
         { 0x01BAU,0x02A3U,0x03E2U,0x05DCU,0x05DCU },             /* au16AirFlow */
         { 0x00ABU,0x009DU,0x009AU,0x009AU,0x009AU },             /* au16Factor_Y0 */
         { 0x00B2U,0x00AAU,0x009BU,0x009BU,0x009BU },             /* au16Factor_Y1 */
         { 0x00ACU,0x00A3U,0x009AU,0x009AU,0x009AU },             /* au16Factor_Y2 */
         { 0x00BDU,0x00BDU,0x00BDU,0x00BDU,0x00BDU },             /* au16Factor_Y3 */
         { 0x00ACU,0x00ACU,0x00ACU,0x00ACU,0x00ACU },             /* au16Factor_Y4 */
         { 0x02B2U,0x02B2U,0x02B2U,0x02B2U,0x02B2U },             /* au16HeatcoreOffset */
         { 0x00C8U,0x012CU,0x0190U },                             /* au16EvapTemp */
         { 0x02B2U,0x02EEU,0x0352U },                             /* au16PFactor_X */
         { 0x0050U,0x006EU,0x0096U },                             /* au16PFactor_Y0 */
         { 0x004BU,0x0069U,0x008CU },                             /* au16PFactor_Y1 */
         { 0x0046U,0x0064U,0x0082U },                             /* au16PFactor_Y2 */
         { 0x0014U,0x003CU,0x0064U },                             /* au16BumpSpeed */
         { 0x0061U,0x007EU,0x00A6U,0x0140U,0x01C6U,0x0232U,0x0302U,0x0377U,0x03BFU,0x03EDU },  /* au16HctPtaTranslate_X */
         { 0x0578U,0x0514U,0x04B0U,0x03B6U,0x0320U,0x02BCU,0x01F4U,0x015EU,0x00C8U,0x0000U },  /* au16HctPtaTranslate_Y */
         { 0x00C8U,0x00FAU,0x015EU,0x0190U,0x0226U,0x02BCU },     /* au16BaseBumpSpdOAT */
         { 0x0050U,0x0050U,0x0050U,0x0050U,0x0050U,0x0050U },     /* au16BaseBumpSpd */
         { 0x0154U,0x01EAU,0x024EU,0x0280U,0x02B2U,0x0316U,0x03ACU },  /* au16DeltaHct */
         { 0x0064U,0x0064U,0x0064U,0x0064U,0x005AU,0x0050U,0x0050U },  /* au16DeltaHctOffset */
         { 0x00C8U,0x00FAU,0x015EU,0x0190U,0x0226U,0x02BCU },     /* au16BaseBumpSpdOATForFactor */
         { 0x0064U,0x0064U,0x0064U,0x0014U,0x0000U,0x0000U }      /* au16DeltaHctOffsetFactor */
      },
      0x8U,                                                       /* u8AddChkSum */
      0xD6U                                                       /* u8XorChkSum */
   }
};


