/********************* MODULE STRUCTURE DEFINITIONS *************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 30/06/2015  13:53:15                                     */
/**           By : test                                                     */
/**        Using : Hct_Cfg_Template_Release_A10.xls                         */
/**         From : D:\HVACProject\Geely F3-3Z\MISR_C_Test_Project\ATC\Sources\HCT\EEPROM*/
/**               (D = )                                                    */
/****************************************************************************/
/*****************************************************************************
* FILE DECLARATION
******************************************************************************/
#ifndef HCT_CFG_H
#define HCT_CFG_H
/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
******************************************************************************/
/* System-headerfiles */

#include "General.h"


/*****************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/

#define  HCT_nBumpSpeed_Len    (3U)
#define  HCT_nAirFlow_Len    (5U)
#define  HCT_nFactor_Y0_Len    (5U)
#define  HCT_nFactor_Y1_Len    (5U)
#define  HCT_nFactor_Y2_Len    (5U)
#define  HCT_nFactor_Y3_Len    (5U)
#define  HCT_nFactor_Y4_Len    (5U)
#define  HCT_nHeatcoreOffset_Len    (6U)
#define  HCT_nEvapTempTbl_Len    (3U)
#define  HCT_nPfactorTbl_Len    (3U)
#define  HCT_nPfactorTbl_Len    (3U)
#define  HCT_nBumpSpeedTble_Len    (3U)
#define  HCT_nHctPtaTranslate_X_Len    (10U)
#define  HCT_nHctPtaTranslate_Y_Len    (10U)
#define  HCT_nBaseBumpSpdOAT_Len    (6U)
#define  HCT_nBaseBumpSpd_Len    (6U)
#define  HCT_nDeltaHct_Len    (7U)
#define  HCT_nDeltaHctOffset_Len    (7U)
#define  HCT_nBaseBumpSpdOATForFactor_Len    (6U)
#define  HCT_nDeltaHctOffsetFactor_Len    (6U)

/*************************** Define Structures Arrary length ************************/

typedef struct HCT_stHctInfo
{
   uint8    u8VariableConst;
   uint8    u8ChipType;
   uint8    u8HeaderFillByte1;
   uint8    u8HeaderFillByte2;
} HCT_tstHctInfo;

typedef struct HCT_stHctData
{
   uint16   au16BumpSpeed_Tbl [ HCT_nBumpSpeed_Len ];
   uint16   au16AirFlow [ HCT_nAirFlow_Len ];
   uint16   au16Factor_Y0 [ HCT_nFactor_Y0_Len ];
   uint16   au16Factor_Y1 [ HCT_nFactor_Y1_Len ];
   uint16   au16Factor_Y2 [ HCT_nFactor_Y2_Len ];
   uint16   au16Factor_Y3 [ HCT_nFactor_Y3_Len ];
   uint16   au16Factor_Y4 [ HCT_nFactor_Y4_Len ];
   uint16   au16HeatcoreOffset [ HCT_nHeatcoreOffset_Len ];
   uint16   au16EvapTemp [ HCT_nEvapTempTbl_Len ];
   uint16   au16PFactor_X [ HCT_nPfactorTbl_Len ];
   uint16   au16PFactor_Y0 [ HCT_nPfactorTbl_Len ];
   uint16   au16PFactor_Y1 [ HCT_nPfactorTbl_Len ];
   uint16   au16PFactor_Y2 [ HCT_nPfactorTbl_Len ];
   uint16   au16BumpSpeed [ HCT_nBumpSpeedTble_Len ];
   uint16   au16HctPtaTranslate_X [ HCT_nHctPtaTranslate_X_Len ];
   uint16   au16HctPtaTranslate_Y [ HCT_nHctPtaTranslate_Y_Len ];
   uint16   au16BaseBumpSpdOAT [ HCT_nBaseBumpSpdOAT_Len ];
   uint16   au16BaseBumpSpd [ HCT_nBaseBumpSpd_Len ];
   uint16   au16DeltaHct [ HCT_nDeltaHct_Len ];
   uint16   au16DeltaHctOffset [ HCT_nDeltaHctOffset_Len ];
   uint16   au16BaseBumpSpdOATForFactor [ HCT_nBaseBumpSpdOATForFactor_Len ];
   uint16   au16DeltaHctOffsetFactor [ HCT_nDeltaHctOffsetFactor_Len ];
} HCT_tstHctData;

/*************************** Group Structures ************************/
typedef struct HCT_stGroup1
{
   HCT_tstHctInfo  stHctInfo;
   HCT_tstHctData  stHctData;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} HCT_tstGroup1;

/********************** LAYOUT STRUCTURE ****************************/
typedef struct 
{
   HCT_tstGroup1  stGroup1;
} HCT_tstLayout;


extern HCT_tstLayout HCT_stLayout;

/********************* VARIABLE ACCESS MACROS ***************************/
#define   HCT_u8Group1VariableConst               (HCT_stLayout.stGroup1.stHctInfo.u8VariableConst)
#define   HCT_u8Group1ChipType                    (HCT_stLayout.stGroup1.stHctInfo.u8ChipType)
#define   HCT_u8Group1HeaderFillByte1             (HCT_stLayout.stGroup1.stHctInfo.u8HeaderFillByte1)
#define   HCT_u8Group1HeaderFillByte2             (HCT_stLayout.stGroup1.stHctInfo.u8HeaderFillByte2)
#define   HCT_au16Group1BumpSpeed_Tbl             (HCT_stLayout.stGroup1.stHctData.au16BumpSpeed_Tbl)
#define   HCT_au16Group1AirFlow                   (HCT_stLayout.stGroup1.stHctData.au16AirFlow)
#define   HCT_au16Group1Factor_Y0                 (HCT_stLayout.stGroup1.stHctData.au16Factor_Y0)
#define   HCT_au16Group1Factor_Y1                 (HCT_stLayout.stGroup1.stHctData.au16Factor_Y1)
#define   HCT_au16Group1Factor_Y2                 (HCT_stLayout.stGroup1.stHctData.au16Factor_Y2)
#define   HCT_au16Group1Factor_Y3                 (HCT_stLayout.stGroup1.stHctData.au16Factor_Y3)
#define   HCT_au16Group1Factor_Y4                 (HCT_stLayout.stGroup1.stHctData.au16Factor_Y4)
#define   HCT_au16Group1HeatcoreOffset            (HCT_stLayout.stGroup1.stHctData.au16HeatcoreOffset)
#define   HCT_au16Group1EvapTemp                  (HCT_stLayout.stGroup1.stHctData.au16EvapTemp)
#define   HCT_au16Group1PFactor_X                 (HCT_stLayout.stGroup1.stHctData.au16PFactor_X)
#define   HCT_au16Group1PFactor_Y0                (HCT_stLayout.stGroup1.stHctData.au16PFactor_Y0)
#define   HCT_au16Group1PFactor_Y1                (HCT_stLayout.stGroup1.stHctData.au16PFactor_Y1)
#define   HCT_au16Group1PFactor_Y2                (HCT_stLayout.stGroup1.stHctData.au16PFactor_Y2)
#define   HCT_au16Group1BumpSpeed                 (HCT_stLayout.stGroup1.stHctData.au16BumpSpeed)
#define   HCT_au16Group1HctPtaTranslate_X          (HCT_stLayout.stGroup1.stHctData.au16HctPtaTranslate_X)
#define   HCT_au16Group1HctPtaTranslate_Y          (HCT_stLayout.stGroup1.stHctData.au16HctPtaTranslate_Y)
#define   HCT_au16Group1BaseBumpSpdOAT            (HCT_stLayout.stGroup1.stHctData.au16BaseBumpSpdOAT)
#define   HCT_au16Group1BaseBumpSpd               (HCT_stLayout.stGroup1.stHctData.au16BaseBumpSpd)
#define   HCT_au16Group1DeltaHct                  (HCT_stLayout.stGroup1.stHctData.au16DeltaHct)
#define   HCT_au16Group1DeltaHctOffset            (HCT_stLayout.stGroup1.stHctData.au16DeltaHctOffset)
#define   HCT_au16Group1BaseBumpSpdOATForFactor          (HCT_stLayout.stGroup1.stHctData.au16BaseBumpSpdOATForFactor)
#define   HCT_au16Group1DeltaHctOffsetFactor          (HCT_stLayout.stGroup1.stHctData.au16DeltaHctOffsetFactor)
#define   HCT_nDadaOffset                         (640U)    /**/
#define   HCT_nZeroTempOffset                     (400U)    /**/
#define   HCT_nCoolantDefaultValue                (1300U)    /*90*10+400*/
#define   HCT_nDampingTemp                        (850U)    /*45*10+400*/
#define   HCT_nMaxDeltaHct                        (10U)    /*1¡æ*/
#define   HCT_nMaxHctIntegral                     (200U)    /*20¡æ*/
#define   HCT_nFilterTime                         (10U)    /**/
#define   HCT_nTboLowLimit                        (450U)    /**/
#define   HCT_nTboHighLimit                       (500U)    /**/
#define   HCT_nIFactor                            (1U)    /**/
#define   HCT_nMaxPValue                          (300U)    /**/
#define   HCT_nMaxIValue                          (300U)    /**/
#define   HCT_nAirDisFace                         (0U)    /**/
#define   HCT_nAirDisBilevel                      (1U)    /**/
#define   HCT_nAirDisFloor                        (2U)    /**/
#define   HCT_nAirDisMixed                        (3U)    /**/
#define   HCT_nAirDisScreen                       (4U)    /**/
#define   HCT_nModeOff                            (0U)    /**/
#define   HCT_nSetTempLo                          (0U)    /**/
/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*HCT_Cfg.h
******************************************************************************/
