/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2016/4/7  19:24:20                                       */
/**           By : uidp3721                                                 */
/**        Using : ISTP_Cfg_Template_Release_A10.xls                        */
/**         From : D:\HVACProject\Geely\KC-2\ATC\01_Application\02_Sources\01_CC\01_APP\ISTP*/
/**               (D = )                                                    */
/**************************************************************************************/

/**************************************************************************************
 Module Name : ISTP
 File Name : ISTP_Cfg.c
--------------------------------------------------------------------------------------
               C O P Y R I G H T
--------------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.    All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 ------------------------------------------------------------------------------------
  Name                                          Company
  -----------------------------          ---------------------------------------
 uidp3721                              Desay SV Automotive Co., Ltd
  -----------------------------          ---------------------------------------
***************************************************************************************/
/*Module Define*/
#define ISTP_CFG

/*Header file */
#include "ISTP_Cfg.h"

/***************************************************************************************
*MODULE GLOBAL CONFIGURATION CONSTANTS
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
***************************************************************************************/


 ISTP_tstLayout ISTP_stLayout;


 const ISTP_tstLayout ISTP_stDefaultLayout = {

   {  /*----------------------- GroupISTP ---------------------------------------*/

      {  /* IstpInfo */
         0x0U,                                                    /* u8VariableConst */
         0x1U,                                                    /* u8ChipType */
         0xFFU,                                                   /* u8HeaderFillByte1 */
         0xFFU                                                    /* u8HeaderFillByte2 */
      },

      {  /* IstpData */
         { 0x0064U,0x00C8U,0x012CU,0x015EU,0x0190U,0x01F4U,0x0226U },  /* au16OatBoDiffHX_Tbl */
         { 0x021CU,0x021CU,0x021CU,0x021CU,0x021CU,0x021CU,0x021CU },  /* au16OatBoDiffHY_Tbl */
         { 0x01C2U,0x01F4U,0x0226U,0x0158U,0x028AU,0x02BCU,0x02EEU },  /* au16OatBoDiffCX_Tbl */
         { 0x017CU,0x0168U,0x0154U,0x014AU,0x0140U,0x0136U,0x0136U },  /* au16OatBoDiffCY_Tbl */
         { 0x0064U,0x00C8U,0x012CU,0x0190U,0x01F4U,0x0258U,0x02BCU,0x0320U },  /* au16OatIRTimerCX_Tbl */
         { 0x001EU,0x001EU,0x001EU,0x001EU,0x0019U,0x0014U,0x0002U,0x0002U },  /* au16OatIRTimerCY_Tbl */
         { 0x0064U,0x00C8U,0x012CU,0x0190U,0x01F4U,0x0258U,0x01BCU,0x0320U },  /* au16OatIRTimerHX_Tbl */
         { 0x0028U,0x0028U,0x002DU,0x003CU,0x0050U,0x0050U,0x0050U,0x0050U },  /* au16OatIRTimerHY_Tbl */
         { 0x14U,0x28U,0x3CU,0x50U,0x64U,0x78U,0x8CU },           /* au8BctlIRTimerFactorX_Tbl */
         { 0x80U,0x80U,0x80U,0x80U,0x80U,0x80U,0x80U },           /* au8BctlIRTimerFactorY_Tbl */
         { 0x0064U,0x00C8U,0x012CU,0x0190U,0x01F4U,0x0258U,0x02BCU,0x0320U },  /* au16BlowerOatLimitX_Tbl */
         { 0x0014U,0x0014U,0x001DU,0x001DU,0x0023U,0x0028U,0x002DU,0x002DU },  /* au16BlowerOatLimitY_Tbl */
         { 0x0064U,0x0190U,0x02BCU,0x03E8U },                     /* au16SunTempOffsX_Tbl */
         { 0x0190U,0x0190U,0x0190U,0x0190U },                     /* au16SunTempOffsY1_Tbl */
         { 0x0190U,0x0190U,0x0190U,0x0190U },                     /* au16SunTempOffsY2_Tbl */
         { 0x0190U,0x0190U,0x0190U,0x0190U },                     /* au16SunTempOffsY3_Tbl */
         { 0x0190U,0x0190U,0x0190U,0x0190U },                     /* au16SunTempOffsY4_Tbl */
         { 0x00FAU,0x0190U,0x0276U,0x02BCU },                     /* au16SunTempOatX_Tbl */
         { 0x0064U,0x0190U,0x02BCU,0x03E8U },                     /* au16SunBctlOffsX_Tbl */
         { 0x0000U,0x0000U,0x0000U,0x0000U },                     /* au16SunBctlOffsY1_Tbl */
         { 0x0000U,0x0000U,0x0000U,0x0000U },                     /* au16SunBctlOffsY2_Tbl */
         { 0x0000U,0x0000U,0x0000U,0x0000U },                     /* au16SunBctlOffsY3_Tbl */
         { 0x0000U,0x0000U,0x0000U,0x0000U }                      /* au16SunBctlOffsY4_Tbl */
      },
      0x6DU,                                                      /* u8AddChkSum */
      0x8DU                                                       /* u8XorChkSum */
   },

   {  /*----------------------- GroupISTP1 ---------------------------------------*/

      {  /* ModeVarSelect */
         0x0U,                                                    /* u8VariableConst */
         0xFFU,                                                   /* u8VCFillByte1 */
         0xFFU,                                                   /* u8VCFillByte2 */
         0xFFU                                                    /* u8VCFillByte3 */
      },

      {  /* ModelVariant */
         0x2U,                                                    /* u8ModelType */
         0x0U                                                     /* u8VWType */
      },
      0x0U,                                                       /* u8AddChkSum */
      0xFEU                                                       /* u8XorChkSum */
   }
};


 const ISTP_tstRomLayout ISTP_stRomLayout = {

   {  /*----------------------- GroupISTP2 ---------------------------------------*/

      {  /* MMIVarSelect */
         0x1U,                                                    /* u8VariableConst */
         0xFFU,                                                   /* u8VCFillByte1 */
         0xFFU,                                                   /* u8VCFillByte2 */
         0xFFU                                                    /* u8VCFillByte3 */
      },

      {  /* MMISaveData */
         { 0x0U,0x0U }                                            /* au8MMISaveData */
      },
      0x1U,                                                       /* u8AddChkSum */
      0xFFU                                                       /* u8XorChkSum */
   },

   {  /*----------------------- GroupISTP3 ---------------------------------------*/

      {  /* SHCVarSelect */
         0x1U,                                                    /* u8VariableConst */
         0xFFU,                                                   /* u8VCFillByte1 */
         0xFFU,                                                   /* u8VCFillByte2 */
         0xFFU                                                    /* u8VCFillByte3 */
      },

      {  /* SHCCalibration */
         { 0xFFU,0xFFU },                                         /* au8SHCOutPutVoltage */
         { 0xFFU,0xFFU },                                         /* au8SHCOutPutCurrent */
         0xFFU,                                                   /* u8SHCKParameter */
         0xFFU                                                    /* u8FillByte_SHCCalibration */
      },
      0x7U,                                                       /* u8AddChkSum */
      0xFFU                                                       /* u8XorChkSum */
   }
};
