/************************** DEFAULTS ************************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 03/02/2016  15:25:08                                     */
/**           By : test                                                     */
/**        Using : VKEY2.7_Cfg_Template_Release_A09.xls                     */
/**         From : D:\HVACProject\New Development Model\NDM CODE\VKEY\VKEY_V1.0*/
/**               (D = )                                                    */
/****************************************************************************/

/*****************************************************************************
* FILE DECLARATION
*****************************************************************************/

#define VKEY_CFG

/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
*****************************************************************************/
#include "General.h"
#include "Vkey_Cfg.h"


/*****************************************************************************
* MODULE GLOBAL CONFIGURATION CONSTANTS
*
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
*****************************************************************************/


VKEY_tstLayout VKEY_stLayout;


const VKEY_tstLayout VKEY_stDefaultLayout = {

   {  /*----------------------- Group1 ---------------------------------------*/

      {  /* VKeyInfo */
         0x0U,                                                    /* u8VariableConst */
         0x1U,                                                    /* u8ChipType */
         0xFFU,                                                   /* u8HeaderFillByte1 */
         0xFFU                                                    /* u8HeaderFillByte2 */
      },
      0x0U,                                                       /* u8AddChkSum */
      0x2U                                                        /* u8XorChkSum */
   }
};


