/********************* MODULE STRUCTURE DEFINITIONS *************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 03/02/2016  15:25:08                                     */
/**           By : test                                                     */
/**        Using : VKEY2.7_Cfg_Template_Release_A09.xls                     */
/**         From : D:\HVACProject\New Development Model\NDM CODE\VKEY\VKEY_V1.0*/
/**               (D = )                                                    */
/****************************************************************************/
/*****************************************************************************
* FILE DECLARATION
******************************************************************************/
#ifndef VKEY_CFG_H
#define VKEY_CFG_H
/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
******************************************************************************/
/* System-headerfiles */


/*****************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/



/*************************** Define Structures Arrary length ************************/

typedef struct VKEY_stVKeyInfo
{
   uint8    u8VariableConst;
   uint8    u8ChipType;
   uint8    u8HeaderFillByte1;
   uint8    u8HeaderFillByte2;
} VKEY_tstVKeyInfo;

/*************************** Group Structures ************************/
typedef struct VKEY_stGroup1
{
   VKEY_tstVKeyInfo  stVKeyInfo;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} VKEY_tstGroup1;

/********************** LAYOUT STRUCTURE ****************************/
typedef struct 
{
   VKEY_tstGroup1  stGroup1;
} VKEY_tstLayout;


extern VKEY_tstLayout VKEY_stLayout;

/********************* VARIABLE ACCESS MACROS ***************************/
#define   VKEY_u8Group1VariableConst              (VKEY_stLayout.stGroup1.stVKeyInfo.u8VariableConst)
#define   VKEY_u8Group1ChipType                   (VKEY_stLayout.stGroup1.stVKeyInfo.u8ChipType)
#define   VKEY_u8Group1HeaderFillByte1            (VKEY_stLayout.stGroup1.stVKeyInfo.u8HeaderFillByte1)
#define   VKEY_u8Group1HeaderFillByte2            (VKEY_stLayout.stGroup1.stVKeyInfo.u8HeaderFillByte2)
#define   VKEY_nVariableConst                     (1U)    /**/
#define   VKEY_nMaxKeyNum                         (11U)    /**/
#define   VKEY_nMaxKeyGroup                       (1U)    /**/
/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*VKEY_Cfg.h
******************************************************************************/
