/********************* MODULE STRUCTURE DEFINITIONS *************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 2017/10/20  11:36:47                                     */
/**           By : uidp4501                                                 */
/**        Using : AIRD_Cfg_v01.xls                                         */
/**         From : D:\HVACProject\Geely\FE-5DB&7DA\ProjectCode\01_APP\AIRD  */
/**               (D = )                                                    */
/****************************************************************************/
/*****************************************************************************
* FILE DECLARATION
******************************************************************************/
#ifndef AIRD_CFG_H
#define AIRD_CFG_H
/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
******************************************************************************/
/* System-headerfiles */
#include "General.h"


/*****************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/


#define  AIRD_nAirdManuPositionTbl_Len    (5U)
#define  AIRD_nAirdWinterPositionTbl_Len    (7U)
#define  AIRD_nAirdSummerPositionTbl_Len    (7U)
#define  AIRD_nBlowoutTempTbl_Len    (4U)
#define  AIRD_nBlowoutTempTbl_Len    (4U)
#define  AIRD_nHeatercoreTempTbl_Len    (2U)
#define  AIRD_nHeatercoreTempTbl_Len    (2U)

/*************************** Define Structures Arrary length ************************/

typedef const struct AIRD_stAirdInfo
{
   const uint8    u8VariableConst;
   const uint8    u8ChipType;
} AIRD_tstAirdInfo;

typedef const struct AIRD_stAirdData
{
   const uint16   au16AirdManuPosition_Tbl [ AIRD_nAirdManuPositionTbl_Len ];
   const uint16   au16AirdWinterPosition_Tbl [ AIRD_nAirdWinterPositionTbl_Len ];
   const uint16   au16AirdSummerPosition_Tbl [ AIRD_nAirdSummerPositionTbl_Len ];
   const uint16   au16BlowoutTempDown_Tbl [ AIRD_nBlowoutTempTbl_Len ];
   const uint16   au16BlowoutTempUp_Tbl [ AIRD_nBlowoutTempTbl_Len ];
   const uint16   au16HeatercoreTempDown [ AIRD_nHeatercoreTempTbl_Len ];
   const uint16   au16HeatercoreTempUp [ AIRD_nHeatercoreTempTbl_Len ];
} AIRD_tstAirdData;

/*************************** Group Structures ************************/
typedef const struct AIRD_stGroup1
{
   AIRD_tstAirdInfo  stAirdInfo;
   AIRD_tstAirdData  stAirdData;
   const uint8  u8AddChkSum;
   const uint8  u8XorChkSum;
} AIRD_tstGroup1;

/********************** LAYOUT STRUCTURE ****************************/

typedef const struct 
{
   AIRD_tstGroup1  stGroup1;
} AIRD_tstRomLayout;

extern const AIRD_tstRomLayout AIRD_stRomLayout;

/********************* VARIABLE ACCESS MACROS ***************************/
#define   AIRD_u8Group1VariableConst              (AIRD_stRomLayout.stGroup1.stAirdInfo.u8VariableConst)
#define   AIRD_u8Group1ChipType                   (AIRD_stRomLayout.stGroup1.stAirdInfo.u8ChipType)
#define   AIRD_au16Group1AirdManuPosition_Tbl          (AIRD_stRomLayout.stGroup1.stAirdData.au16AirdManuPosition_Tbl)
#define   AIRD_au16Group1AirdWinterPosition_Tbl          (AIRD_stRomLayout.stGroup1.stAirdData.au16AirdWinterPosition_Tbl)
#define   AIRD_au16Group1AirdSummerPosition_Tbl          (AIRD_stRomLayout.stGroup1.stAirdData.au16AirdSummerPosition_Tbl)
#define   AIRD_au16Group1BlowoutTempDown_Tbl          (AIRD_stRomLayout.stGroup1.stAirdData.au16BlowoutTempDown_Tbl)
#define   AIRD_au16Group1BlowoutTempUp_Tbl          (AIRD_stRomLayout.stGroup1.stAirdData.au16BlowoutTempUp_Tbl)
#define   AIRD_au16Group1HeatercoreTempDown          (AIRD_stRomLayout.stGroup1.stAirdData.au16HeatercoreTempDown)
#define   AIRD_au16Group1HeatercoreTempUp          (AIRD_stRomLayout.stGroup1.stAirdData.au16HeatercoreTempUp)
/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*AIRD_Cfg.h
******************************************************************************/
