/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2018-7-8 0:19:00									 */
/**           By : uidq0760                                    */
/**        Using : MAC_5DB7DA_V3.10.xml                         */
/**         From : D:\HVACProject\Geely\Geely_5DB_7DA_RoadTEST\FE-5DB&7DA_B1.05\ProjectCode\01_APP\MAC                        */
/**               (D = )                                                    */
/**************************************************************************************/
 
/******************************************************************************
Module Name : MAC
File Name : MAC_Cfg.h
-------------------------------------------------------------------------------
               C O P Y R I G H T
-------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.   All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 -------------------------------------------------------------------------------
  Name                                                   Company
  ---------------------          ---------------------------------------
 uidq0760                Desay SV Automotive Co., Ltd
  ---------------------          ---------------------------------------
******************************************************************************/
 
/* Module Define  */
#ifndef MAC_CFG_H
#define MAC_CFG_H

/* System-headerfiles */
#include "General.h"


/******************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/

#define  MAC_nBlowerSelect_Tbl_Len		(3U)
#define  MAC_nDrScaleInFace_Tbl_Len		(20U)
#define  MAC_nDrScaleInBilvl1_Tbl_Len		(20U)
#define  MAC_nDrScaleInBilvl2_Tbl_Len		(20U)
#define  MAC_nDrScaleInBilvl3_Tbl_Len		(20U)
#define  MAC_nDrScaleInFoot_Tbl_Len		(20U)
#define  MAC_nDrScaleInMixed_Tbl_Len		(20U)
#define  MAC_nDrScaleInScreen_Tbl_Len		(20U)
#define  MAC_nPsScaleInFace_Tbl_Len		(20U)
#define  MAC_nPsScaleInBilvl1_Tbl_Len		(20U)
#define  MAC_nPsScaleInBilvl2_Tbl_Len		(20U)
#define  MAC_nPsScaleInBilvl3_Tbl_Len		(20U)
#define  MAC_nPsScaleInFoot_Tbl_Len		(20U)
#define  MAC_nPsScaleInMixed_Tbl_Len		(20U)
#define  MAC_nPsScaleInScreen_Tbl_Len		(20U)
#define  MAC_nDrMixAirDoorPositionY_Len		(20U)
#define  MAC_nPsMixAirDoorPositionY_Len		(20U)
#define  MAC_nMacLimitPos_Tbl_Len		(2U)


/*************************** Define Structures Arrary length ************************/

typedef struct MAC_stModuleInfo
{
	uint8 u8VariableConst;
	uint8 u8ChipType;
} MAC_tstModuleInfo;

typedef struct MAC_stModuleData
{
	uint16 au16BlowerSelect_Tbl[MAC_nBlowerSelect_Tbl_Len];
	uint16 au16DrScaleInFaceNum_Tbl[MAC_nDrScaleInFace_Tbl_Len];
	uint16 au16DrScaleInFaceFanLowX_Tbl[MAC_nDrScaleInFace_Tbl_Len];
	uint16 au16DrScaleInFaceFanMidX_Tbl[MAC_nDrScaleInFace_Tbl_Len];
	uint16 au16DrScaleInFaceFanHighX_Tbl[MAC_nDrScaleInFace_Tbl_Len];
	uint16 au16DrScaleInBilvl1Num_Tbl[MAC_nDrScaleInBilvl1_Tbl_Len];
	uint16 au16DrScaleInBilvl1FanLowX_Tbl[MAC_nDrScaleInBilvl1_Tbl_Len];
	uint16 au16DrScaleInBilvl1FanMidX_Tbl[MAC_nDrScaleInBilvl1_Tbl_Len];
	uint16 au16DrScaleInBilvl1FanHighX_Tbl[MAC_nDrScaleInBilvl1_Tbl_Len];
	uint16 au16DrScaleInBilvl2Num_Tbl[MAC_nDrScaleInBilvl2_Tbl_Len];
	uint16 au16DrScaleInBilvl2FanLowX_Tbl[MAC_nDrScaleInBilvl2_Tbl_Len];
	uint16 au16DrScaleInBilvl2FanMidX_Tbl[MAC_nDrScaleInBilvl2_Tbl_Len];
	uint16 au16DrScaleInBilvl2FanHighX_Tbl[MAC_nDrScaleInBilvl2_Tbl_Len];
	uint16 au16DrScaleInBilvl3Num_Tbl[MAC_nDrScaleInBilvl3_Tbl_Len];
	uint16 au16DrScaleInBilvl3FanLowX_Tbl[MAC_nDrScaleInBilvl3_Tbl_Len];
	uint16 au16DrScaleInBilvl3FanMidX_Tbl[MAC_nDrScaleInBilvl3_Tbl_Len];
	uint16 au16DrScaleInBilvl3FanHighX_Tbl[MAC_nDrScaleInBilvl3_Tbl_Len];
	uint16 au16DrScaleInFootNum_Tbl[MAC_nDrScaleInFoot_Tbl_Len];
	uint16 au16DrScaleInFootFanLowX_Tbl[MAC_nDrScaleInFoot_Tbl_Len];
	uint16 au16DrScaleInFootFanMidX_Tbl[MAC_nDrScaleInFoot_Tbl_Len];
	uint16 au16DrScaleInFootFanHighX_Tbl[MAC_nDrScaleInFoot_Tbl_Len];
	uint16 au16DrScaleInMixed_Tbl[MAC_nDrScaleInMixed_Tbl_Len];
	uint16 au16DrScaleInScreen_Tbl[MAC_nDrScaleInScreen_Tbl_Len];
	uint16 au16PsScaleInFaceNum_Tbl[MAC_nPsScaleInFace_Tbl_Len];
	uint16 au16PsScaleInFaceFanLowX_Tbl[MAC_nPsScaleInFace_Tbl_Len];
	uint16 au16PsScaleInFaceFanMidX_Tbl[MAC_nPsScaleInFace_Tbl_Len];
	uint16 au16PsScaleInFaceFanHighX_Tbl[MAC_nPsScaleInFace_Tbl_Len];
	uint16 au16PsScaleInBilvl1Num_Tbl[MAC_nPsScaleInBilvl1_Tbl_Len];
	uint16 au16PsScaleInBilvl1FanLowX_Tbl[MAC_nPsScaleInBilvl1_Tbl_Len];
	uint16 au16PsScaleInBilvl1FanMidX_Tbl[MAC_nPsScaleInBilvl1_Tbl_Len];
	uint16 au16PsScaleInBilvl1FanHighX_Tbl[MAC_nPsScaleInBilvl1_Tbl_Len];
	uint16 au16PsScaleInBilvl2Num_Tbl[MAC_nPsScaleInBilvl2_Tbl_Len];
	uint16 au16PsScaleInBilvl2FanLowX_Tbl[MAC_nPsScaleInBilvl2_Tbl_Len];
	uint16 au16PsScaleInBilvl2FanMidX_Tbl[MAC_nPsScaleInBilvl2_Tbl_Len];
	uint16 au16PsScaleInBilvl2FanHighX_Tbl[MAC_nPsScaleInBilvl2_Tbl_Len];
	uint16 au16PsScaleInBilvl3Num_Tbl[MAC_nPsScaleInBilvl3_Tbl_Len];
	uint16 au16PsScaleInBilvl3FanLowX_Tbl[MAC_nPsScaleInBilvl3_Tbl_Len];
	uint16 au16PsScaleInBilvl3FanMidX_Tbl[MAC_nPsScaleInBilvl3_Tbl_Len];
	uint16 au16PsScaleInBilvl3FanHighX_Tbl[MAC_nPsScaleInBilvl3_Tbl_Len];
	uint16 au16PsScaleInFootNum_Tbl[MAC_nPsScaleInFoot_Tbl_Len];
	uint16 au16PsScaleInFootFanLowX_Tbl[MAC_nPsScaleInFoot_Tbl_Len];
	uint16 au16PsScaleInFootFanMidX_Tbl[MAC_nPsScaleInFoot_Tbl_Len];
	uint16 au16PsScaleInFootFanHighX_Tbl[MAC_nPsScaleInFoot_Tbl_Len];
	uint16 au16PsScaleInMixed_Tbl[MAC_nPsScaleInMixed_Tbl_Len];
	uint16 au16PsScaleInScreen_Tbl[MAC_nPsScaleInScreen_Tbl_Len];
	uint16 au16DrMixAirDoorPositionY[MAC_nDrMixAirDoorPositionY_Len];
	uint16 au16PsMixAirDoorPositionY[MAC_nPsMixAirDoorPositionY_Len];
	uint16 au16MacLimitPosX_Tbl[MAC_nMacLimitPos_Tbl_Len];
	uint16 au16MacLimitPosY_Tbl[MAC_nMacLimitPos_Tbl_Len];
} MAC_tstModuleData;

typedef struct MAC_stMacro
{
	uint16 u16EvapHysteresis;
	uint16 u16HctHysteresis;
	uint16 u16MacPosiHysteresis;
	uint16 u16BlowerHysteresis;
	uint16 u16HctEvapMinDiff;
} MAC_tstMacro;



/*************************** Group Structures ************************/

typedef struct MAC_stGroup1
{
	MAC_tstModuleInfo	stModuleInfo;
	MAC_tstModuleData	stModuleData;
	MAC_tstMacro	stMacro;
	uint8 u8AddChkSum;
	uint8  u8XorChkSum;
} MAC_tstGroup1;



/********************** LAYOUT STRUCTURE ****************************/



typedef struct
{
	MAC_tstGroup1	stGroup1;
} MAC_tstRomLayout;

extern const MAC_tstRomLayout MAC_stRomLayout;


/********************* VARIABLE ACCESS MACROS ***************************/

#define   MAC_u8Group1VariableConst		(MAC_stRomLayout.stGroup1.stModuleInfo.u8VariableConst)
#define   MAC_u8Group1ChipType		(MAC_stRomLayout.stGroup1.stModuleInfo.u8ChipType)
#define   MAC_au16Group1BlowerSelect_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16BlowerSelect_Tbl)
#define   MAC_au16Group1DrScaleInFaceNum_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInFaceNum_Tbl)
#define   MAC_au16Group1DrScaleInFaceFanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInFaceFanLowX_Tbl)
#define   MAC_au16Group1DrScaleInFaceFanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInFaceFanMidX_Tbl)
#define   MAC_au16Group1DrScaleInFaceFanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInFaceFanHighX_Tbl)
#define   MAC_au16Group1DrScaleInBilvl1Num_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl1Num_Tbl)
#define   MAC_au16Group1DrScaleInBilvl1FanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl1FanLowX_Tbl)
#define   MAC_au16Group1DrScaleInBilvl1FanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl1FanMidX_Tbl)
#define   MAC_au16Group1DrScaleInBilvl1FanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl1FanHighX_Tbl)
#define   MAC_au16Group1DrScaleInBilvl2Num_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl2Num_Tbl)
#define   MAC_au16Group1DrScaleInBilvl2FanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl2FanLowX_Tbl)
#define   MAC_au16Group1DrScaleInBilvl2FanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl2FanMidX_Tbl)
#define   MAC_au16Group1DrScaleInBilvl2FanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl2FanHighX_Tbl)
#define   MAC_au16Group1DrScaleInBilvl3Num_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl3Num_Tbl)
#define   MAC_au16Group1DrScaleInBilvl3FanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl3FanLowX_Tbl)
#define   MAC_au16Group1DrScaleInBilvl3FanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl3FanMidX_Tbl)
#define   MAC_au16Group1DrScaleInBilvl3FanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInBilvl3FanHighX_Tbl)
#define   MAC_au16Group1DrScaleInFootNum_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInFootNum_Tbl)
#define   MAC_au16Group1DrScaleInFootFanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInFootFanLowX_Tbl)
#define   MAC_au16Group1DrScaleInFootFanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInFootFanMidX_Tbl)
#define   MAC_au16Group1DrScaleInFootFanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInFootFanHighX_Tbl)
#define   MAC_au16Group1DrScaleInMixed_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInMixed_Tbl)
#define   MAC_au16Group1DrScaleInScreen_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16DrScaleInScreen_Tbl)
#define   MAC_au16Group1PsScaleInFaceNum_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInFaceNum_Tbl)
#define   MAC_au16Group1PsScaleInFaceFanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInFaceFanLowX_Tbl)
#define   MAC_au16Group1PsScaleInFaceFanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInFaceFanMidX_Tbl)
#define   MAC_au16Group1PsScaleInFaceFanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInFaceFanHighX_Tbl)
#define   MAC_au16Group1PsScaleInBilvl1Num_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl1Num_Tbl)
#define   MAC_au16Group1PsScaleInBilvl1FanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl1FanLowX_Tbl)
#define   MAC_au16Group1PsScaleInBilvl1FanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl1FanMidX_Tbl)
#define   MAC_au16Group1PsScaleInBilvl1FanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl1FanHighX_Tbl)
#define   MAC_au16Group1PsScaleInBilvl2Num_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl2Num_Tbl)
#define   MAC_au16Group1PsScaleInBilvl2FanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl2FanLowX_Tbl)
#define   MAC_au16Group1PsScaleInBilvl2FanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl2FanMidX_Tbl)
#define   MAC_au16Group1PsScaleInBilvl2FanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl2FanHighX_Tbl)
#define   MAC_au16Group1PsScaleInBilvl3Num_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl3Num_Tbl)
#define   MAC_au16Group1PsScaleInBilvl3FanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl3FanLowX_Tbl)
#define   MAC_au16Group1PsScaleInBilvl3FanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl3FanMidX_Tbl)
#define   MAC_au16Group1PsScaleInBilvl3FanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInBilvl3FanHighX_Tbl)
#define   MAC_au16Group1PsScaleInFootNum_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInFootNum_Tbl)
#define   MAC_au16Group1PsScaleInFootFanLowX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInFootFanLowX_Tbl)
#define   MAC_au16Group1PsScaleInFootFanMidX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInFootFanMidX_Tbl)
#define   MAC_au16Group1PsScaleInFootFanHighX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInFootFanHighX_Tbl)
#define   MAC_au16Group1PsScaleInMixed_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInMixed_Tbl)
#define   MAC_au16Group1PsScaleInScreen_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16PsScaleInScreen_Tbl)
#define   MAC_au16Group1DrMixAirDoorPositionY		(MAC_stRomLayout.stGroup1.stModuleData.au16DrMixAirDoorPositionY)
#define   MAC_au16Group1PsMixAirDoorPositionY		(MAC_stRomLayout.stGroup1.stModuleData.au16PsMixAirDoorPositionY)
#define   MAC_au16Group1MacLimitPosX_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16MacLimitPosX_Tbl)
#define   MAC_au16Group1MacLimitPosY_Tbl		(MAC_stRomLayout.stGroup1.stModuleData.au16MacLimitPosY_Tbl)
#define   MAC_u16Group1EvapHysteresis		(MAC_stRomLayout.stGroup1.stMacro.u16EvapHysteresis)
#define   MAC_u16Group1HctHysteresis		(MAC_stRomLayout.stGroup1.stMacro.u16HctHysteresis)
#define   MAC_u16Group1MacPosiHysteresis		(MAC_stRomLayout.stGroup1.stMacro.u16MacPosiHysteresis)
#define   MAC_u16Group1BlowerHysteresis		(MAC_stRomLayout.stGroup1.stMacro.u16BlowerHysteresis)
#define   MAC_u16Group1HctEvapMinDiff		(MAC_stRomLayout.stGroup1.stMacro.u16HctEvapMinDiff)




/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*MAC_Cfg.h
******************************************************************************/

