/************************** DEFAULTS ************************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 2017/10/24  19:21:21                                     */
/**           By : uidp4501                                                 */
/**        Using : Dim_Cfg.xls                                              */
/**         From : D:\HVACProject\Geely\FE-5DB&7DA\ProjectCode\01_APP\DIM   */
/**               (D = )                                                    */
/****************************************************************************/

/*****************************************************************************
* FILE DECLARATION
*****************************************************************************/

#define DIM_CFG

/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
*****************************************************************************/
#include "DIM.h"


/*****************************************************************************
* MODULE GLOBAL CONFIGURATION CONSTANTS
*
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
*****************************************************************************/




const DIM_tstRomLayout DIM_stRomLayout = {

   {  /*----------------------- Group1 ---------------------------------------*/

      {  /* DimInfo */
         0x1U,                                                    /* u8VariableConst */
         0x1U                                                     /* u8ChipType */
      },
      0xFDU,                                                      /* u8AddChkSum */
      0x1U                                                        /* u8XorChkSum */
   }
};
