/* -----------------------------------------------------------------------------
  Filename:    appdesc.h
  Description: Interface towards the application used by CANdesc.
                
                Manufacturer: BAIC
                EcuDocFile:   D:\HVACProject\Geely\KC_2\Gney\Geely_KC-2_013.cdd
                Variant:      CommonDiagnostics

  Generated by CANdelaGen, Tue Jan 03 13:38:58 2017
 
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2012 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------*/
#ifndef APPDESC1C1_H
#define APPDESC1C1_H

typedef enum DIAG_enu8VarNumbers
{   
	DIAG_nu8SwVersion=0,
	DIAG_nu8KeepAlive,  
	DIAG_nu8EngType,
	DIAG_nu8AQSMount,           
	DIAG_nu8PM25Mount, 
	DIAG_nu8IONMount, 	
	DIAG_nu8RCPMount,
	DIAG_nu8AppRxDisable,
	DIAG_nu8AppTxDisable,/*Added by Yang Shengli,20170715*/
	DIAG_nu8NmRxDisable,/*Added by Yang Shengli,20170715*/
	DIAG_nu8ResetFlag,
	DIAG_nu8SelfTestReq,
	DIAG_nu8Max                   
}DIAG_tenu8VarNumber;
uint8 DIAG_u8GetValue( DIAG_tenu8VarNumber enIndex );
Std_ReturnType DIAG_FunctionCf(uint8* Res);

#endif /* __APPDESC_H__ */
