/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2016/7/7  18:55:27                                       */
/**           By : uidp3717                                                 */
/**        Using : Diag_Cfg_V1.2.xls                                        */
/**         From : D:\HVACProject\Geely\KC_2\ATC\01_Application\02_Sources\01_CC\02_COM\CAN\DIAG*/
/**               (D = )                                                    */
/**************************************************************************************/
 
/******************************************************************************
Module Name : Diag
File Name : Diag_Cfg.h
-------------------------------------------------------------------------------
               C O P Y R I G H T
-------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.   All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 -------------------------------------------------------------------------------
  Name                                                   Company
  ---------------------          ---------------------------------------
 uidp3717                         Desay SV Automotive Co., Ltd
  ---------------------          ---------------------------------------
******************************************************************************/
 
/* Module Define  */
#ifndef Diag_CFG_H
#define Diag_CFG_H

/* System-headerfiles */
#include "General.h"


/******************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/

#define  Diag_nVehicleName_Len    (8U)
#define  Diag_nSystemNameOrEngineType_Len    (8U)
#define  Diag_nvehicleIdentificationNumber_Len    (17U)
#define  Diag_nVehicleNetworkConfiguration_Len    (8U)
#define  Diag_nReservedValue_Len    (12U)
#define  Diag_nECUInstallationDateDataIdentifier_Len    (4U)
#define  Diag_nBackupCfgInfor_len    (64U)
#define  Diag_nFunctionCfg_Len    (4U)
#define  Diag_nECUManufacturingDate_Len    (4U)
#define  Diag_nECUSerialNumber_Len    (16U)
#define  Diag_nHardWareVersion_Len    (16U)

/*************************** Define Structures Arrary length ************************/

typedef struct Diag_stDiagInfo
{
   uint8    u8VariableConst;
   uint8    u8ModuleID;
   uint16   u16ModuleLen;
} Diag_tstDiagInfo;

typedef struct Diag_stDiagData
{
   uint8    au8VehicleName [ Diag_nVehicleName_Len ];
   uint8    au8SystemNameOrEngineType [ Diag_nSystemNameOrEngineType_Len ];
   uint8    au8vehicleIdentificationNumber [ Diag_nvehicleIdentificationNumber_Len ];
   uint8    au8VehicleNetworkConfiguration [ Diag_nVehicleNetworkConfiguration_Len ];
   uint8    au8ReservedValue [ Diag_nReservedValue_Len ];
   uint8    au8ECUInstallationDateDataIdentifier [ Diag_nECUInstallationDateDataIdentifier_Len ];
   uint8    au8BackupCfgInfor [ Diag_nBackupCfgInfor_len ];
   uint8    au8FunctionCfg [ Diag_nFunctionCfg_Len ];
   uint8    au8ECUManufacturingDate [ Diag_nECUManufacturingDate_Len ];
   uint8    au8ECUSerialNumber [ Diag_nECUSerialNumber_Len ];
   uint8    au8HardWareVersion [ Diag_nHardWareVersion_Len ];
   uint8    u8SecureNrOfAttempts;
} Diag_tstDiagData;

/*************************** Group Structures ************************/
typedef struct Diag_stGroup1
{
   Diag_tstDiagInfo  stDiagInfo;
   Diag_tstDiagData  stDiagData;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} Diag_tstGroup1;

/********************** LAYOUT STRUCTURE ****************************/
typedef struct 
{
   Diag_tstGroup1  stGroup1;
} Diag_tstLayout;


extern Diag_tstLayout Diag_stLayout;
extern const Diag_tstLayout Diag_stDefaultLayout;

/********************* VARIABLE ACCESS MACROS ***************************/
#define   Diag_u8Group1VariableConst              (Diag_stLayout.stGroup1.stDiagInfo.u8VariableConst)
#define   Diag_u8Group1ModuleID                   (Diag_stLayout.stGroup1.stDiagInfo.u8ModuleID)
#define   Diag_u16Group1ModuleLen                 (Diag_stLayout.stGroup1.stDiagInfo.u16ModuleLen)
#define   Diag_au8Group1VehicleName               (Diag_stLayout.stGroup1.stDiagData.au8VehicleName)
#define   Diag_au8Group1SystemNameOrEngineType          (Diag_stLayout.stGroup1.stDiagData.au8SystemNameOrEngineType)
#define   Diag_au8Group1vehicleIdentificationNumber          (Diag_stLayout.stGroup1.stDiagData.au8vehicleIdentificationNumber)
#define   Diag_au8Group1VehicleNetworkConfiguration          (Diag_stLayout.stGroup1.stDiagData.au8VehicleNetworkConfiguration)
#define   Diag_au8Group1ReservedValue             (Diag_stLayout.stGroup1.stDiagData.au8ReservedValue)
#define   Diag_au8Group1ECUInstallationDateDataIdentifier          (Diag_stLayout.stGroup1.stDiagData.au8ECUInstallationDateDataIdentifier)
#define   Diag_au8Group1BackupCfgInfor            (Diag_stLayout.stGroup1.stDiagData.au8BackupCfgInfor)
#define   Diag_au8Group1FunctionCfg               (Diag_stLayout.stGroup1.stDiagData.au8FunctionCfg)
#define   Diag_au8Group1ECUManufacturingDate          (Diag_stLayout.stGroup1.stDiagData.au8ECUManufacturingDate)
#define   Diag_au8Group1ECUSerialNumber           (Diag_stLayout.stGroup1.stDiagData.au8ECUSerialNumber)
#define   Diag_au8Group1HardWareVersion           (Diag_stLayout.stGroup1.stDiagData.au8HardWareVersion)
#define   Diag_u8Group1SecureNrOfAttempts          (Diag_stLayout.stGroup1.stDiagData.u8SecureNrOfAttempts)
/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*Diag_Cfg.h
******************************************************************************/
