/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2016/7/7  18:55:28                                       */
/**           By : uidp3717                                                 */
/**        Using : Diag_Cfg_V1.2.xls                                        */
/**         From : D:\HVACProject\Geely\KC_2\ATC\01_Application\02_Sources\01_CC\02_COM\CAN\DIAG*/
/**               (D = )                                                    */
/**************************************************************************************/

/**************************************************************************************
 Module Name : Diag
 File Name : Diag_Cfg.c
--------------------------------------------------------------------------------------
               C O P Y R I G H T
--------------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.    All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 ------------------------------------------------------------------------------------
  Name                                          Company
  -----------------------------          ---------------------------------------
 uidp3717                              Desay SV Automotive Co., Ltd
  -----------------------------          ---------------------------------------
***************************************************************************************/
/*Module Define*/
#define Diag_CFG

/*Header file */
#include "Diag_Cfg.h"

/***************************************************************************************
*MODULE GLOBAL CONFIGURATION CONSTANTS
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
***************************************************************************************/


 Diag_tstLayout Diag_stLayout;


 const Diag_tstLayout Diag_stDefaultLayout = {

   {  /*----------------------- Group1 ---------------------------------------*/

      {  /* DiagInfo */
         0x00U,                                                   /* u8VariableConst */
         0x08U,                                                   /* u8ModuleID */
         0x00A8U                                                  /* u16ModuleLen */
      },

      {  /* DiagData */
         { 0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U },     /* au8VehicleName */
         { 0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U },     /* au8SystemNameOrEngineType */
         { 0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U },  /* au8vehicleIdentificationNumber */
         { 0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU },     /* au8VehicleNetworkConfiguration */
         { 0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU },  /* au8ReservedValue */
         { 0x20U,0x0U,0x1U,0x1U },                                /* au8ECUInstallationDateDataIdentifier */
         { 0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U,0x0U },  /* au8BackupCfgInfor */
         { 0xFFU,0xFFU,0xFFU,0xFFU },                             /* au8FunctionCfg */
         { 0x20U,0x0U,0x1U,0x1U },                                /* au8ECUManufacturingDate */
         { 0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U,0x20U },  /* au8ECUSerialNumber */
         { 0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU,0xFFU },  /* au8HardWareVersion */
         0xFFU                                                    /* u8SecureNrOfAttempts */
      },
      0x14U,                                                      /* u8AddChkSum */
      0x80U                                                       /* u8XorChkSum */
   }
};


