/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2017/10/27 11:44:26									 */
/**           By : uidp4501                                    */
/**        Using : OAT.xml                         */
/**         From : D:\HVACProject\Geely\FE-5DB&7DA\ProjectCode\01_APP\OAT                        */
/**               (D = )                                                    */
/**************************************************************************************/
 
/******************************************************************************
Module Name : OAT
File Name : OAT_Cfg.h
-------------------------------------------------------------------------------
               C O P Y R I G H T
-------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.   All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 -------------------------------------------------------------------------------
  Name                                                   Company
  ---------------------          ---------------------------------------
 uidp4501                Desay SV Automotive Co., Ltd
  ---------------------          ---------------------------------------
******************************************************************************/
 
/* Module Define  */
#ifndef OAT_CFG_H
#define OAT_CFG_H

/* System-headerfiles */
#include "General.h"


/******************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/

#define  OAT_nOatDiffHctToUpdate_Len		(4U)
#define  OAT_nOatLimitHctToUpdate_Len		(4U)
#define  OAT_nOatSensorAmbient_Len		(10U)
#define  OAT_nOatAqsPtaAmbient_Len		(10U)


/*************************** Define Structures Arrary length ************************/

typedef struct OAT_stModuleInfo
{
	uint16 au16OatDiffHctToUpdate_X[OAT_nOatDiffHctToUpdate_Len];
	uint16 au16OatDiffHctToUpdate_Y[OAT_nOatDiffHctToUpdate_Len];
	uint16 au16OatLimitHctToUpdate_X[OAT_nOatLimitHctToUpdate_Len];
	uint16 au16OatLimitHctToUpdate_Y[OAT_nOatLimitHctToUpdate_Len];
	uint16 au16OatSensorAmbient_X[OAT_nOatSensorAmbient_Len];
	uint16 au16OatSensorAmbient_Y[OAT_nOatSensorAmbient_Len];
	uint16 au16OatAqsPtaAmbient_X[OAT_nOatAqsPtaAmbient_Len];
	uint16 au16OatAqsPtaAmbient_Y[OAT_nOatAqsPtaAmbient_Len];
} OAT_tstModuleInfo;



/*************************** Group Structures ************************/

typedef struct OAT_stGroup1
{
	OAT_tstModuleInfo	stModuleInfo;
	uint8 u8AddChkSum;
	uint8  u8XorChkSum;
} OAT_tstGroup1;



/********************** LAYOUT STRUCTURE ****************************/



typedef struct
{
	OAT_tstGroup1	stGroup1;
} OAT_tstRomLayout;

extern const OAT_tstRomLayout OAT_stRomLayout;


/********************* VARIABLE ACCESS MACROS ***************************/

#define   OAT_au16Group1OatDiffHctToUpdate_X		(OAT_stRomLayout.stGroup1.stModuleInfo.au16OatDiffHctToUpdate_X)
#define   OAT_au16Group1OatDiffHctToUpdate_Y		(OAT_stRomLayout.stGroup1.stModuleInfo.au16OatDiffHctToUpdate_Y)
#define   OAT_au16Group1OatLimitHctToUpdate_X		(OAT_stRomLayout.stGroup1.stModuleInfo.au16OatLimitHctToUpdate_X)
#define   OAT_au16Group1OatLimitHctToUpdate_Y		(OAT_stRomLayout.stGroup1.stModuleInfo.au16OatLimitHctToUpdate_Y)
#define   OAT_au16Group1OatSensorAmbient_X		(OAT_stRomLayout.stGroup1.stModuleInfo.au16OatSensorAmbient_X)
#define   OAT_au16Group1OatSensorAmbient_Y		(OAT_stRomLayout.stGroup1.stModuleInfo.au16OatSensorAmbient_Y)
#define   OAT_au16Group1OatAqsPtaAmbient_X		(OAT_stRomLayout.stGroup1.stModuleInfo.au16OatAqsPtaAmbient_X)
#define   OAT_au16Group1OatAqsPtaAmbient_Y		(OAT_stRomLayout.stGroup1.stModuleInfo.au16OatAqsPtaAmbient_Y)




/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*OAT_Cfg.h
******************************************************************************/