/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2018-3-5 14:28:19									 */
/**           By : uidp4501                                    */
/**        Using : CCS_FE-5DB7DA_V1.2.xml                         */
/**         From : D:\HVACProject\Geely\FE-5DB&7DA\ProjectCode\01_APP\CCS                        */
/**               (D = )                                                    */
/**************************************************************************************/
 
/******************************************************************************
Module Name : CCS
File Name : CCS_Cfg.h
-------------------------------------------------------------------------------
               C O P Y R I G H T
-------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.   All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 -------------------------------------------------------------------------------
  Name                                                   Company
  ---------------------          ---------------------------------------
 uidp4501                Desay SV Automotive Co., Ltd
  ---------------------          ---------------------------------------
******************************************************************************/
 
/* Module Define  */
#ifndef CCS_CFG_H
#define CCS_CFG_H

/* System-headerfiles */
#include "General.h"


/******************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/

#define  CCS_nOatSetTempOffset_Tbl_Len		(6U)
#define  CCS_nOatBlowTempOffset_Tbl_Len		(13U)
#define  CCS_nOatBlowTempSpeedX_Tbl_Len		(4U)
#define  CCS_nSiBlowTempGain_Tbl_Len		(5U)
#define  CCS_nBlowTempOatX_Tbl_Len		(4U)
#define  CCS_nMmiToCcsSetTemp_Tbl_Len		(9U)
#define  CCS_nDrTsetBlowTempGain_Tbl_Len		(7U)
#define  CCS_nPsTsetBlowTempGain_Tbl_Len		(7U)


/*************************** Define Structures Arrary length ************************/

typedef struct CCS_stModuleInfo
{
	uint8 u8VariableConst;
	uint8 u8ChipType;
} CCS_tstModuleInfo;

typedef struct CCS_stModuleData
{
	uint16 au16OatSetTempOffsetX_Tbl[CCS_nOatSetTempOffset_Tbl_Len];
	uint16 au16OatSetTempOffsetY_Tbl[CCS_nOatSetTempOffset_Tbl_Len];
	uint16 au16OatBlowTempOffsetX_Tbl[CCS_nOatBlowTempOffset_Tbl_Len];
	uint16 au16OatBlowTempOffsetY1_Tbl[CCS_nOatBlowTempOffset_Tbl_Len];
	uint16 au16OatBlowTempOffsetY2_Tbl[CCS_nOatBlowTempOffset_Tbl_Len];
	uint16 au16OatBlowTempOffsetY3_Tbl[CCS_nOatBlowTempOffset_Tbl_Len];
	uint16 au16OatBlowTempOffsetY4_Tbl[CCS_nOatBlowTempOffset_Tbl_Len];
	uint16 au16OatBlowTempSpeedX_Tbl[CCS_nOatBlowTempSpeedX_Tbl_Len];
	uint16 au16SiBlowTempGainX_Tbl[CCS_nSiBlowTempGain_Tbl_Len];
	uint16 au16SiBlowTempGainY1_Tbl[CCS_nSiBlowTempGain_Tbl_Len];
	uint16 au16SiBlowTempGainY2_Tbl[CCS_nSiBlowTempGain_Tbl_Len];
	uint16 au16SiBlowTempGainY3_Tbl[CCS_nSiBlowTempGain_Tbl_Len];
	uint16 au16SiBlowTempGainY4_Tbl[CCS_nSiBlowTempGain_Tbl_Len];
	uint16 au16BlowTempOatX_Tbl[CCS_nBlowTempOatX_Tbl_Len];
	uint16 au16MmiToCcsSetTempX_Tbl[CCS_nMmiToCcsSetTemp_Tbl_Len];
	uint16 au16MmiToCcsSetTempY_Tbl[CCS_nMmiToCcsSetTemp_Tbl_Len];
	uint16 au16DrTsetBlowTempGainX_Tbl[CCS_nDrTsetBlowTempGain_Tbl_Len];
	uint16 au16DrTsetBlowTempGainY1_Tbl[CCS_nDrTsetBlowTempGain_Tbl_Len];
	uint16 au16DrTsetBlowTempGainY2_Tbl[CCS_nDrTsetBlowTempGain_Tbl_Len];
	uint16 au16DrTsetBlowTempGainY3_Tbl[CCS_nDrTsetBlowTempGain_Tbl_Len];
	uint16 au16DrTsetBlowTempGainY4_Tbl[CCS_nDrTsetBlowTempGain_Tbl_Len];
	uint16 au16PsTsetBlowTempGainX_Tbl[CCS_nPsTsetBlowTempGain_Tbl_Len];
	uint16 au16PsTsetBlowTempGainY1_Tbl[CCS_nPsTsetBlowTempGain_Tbl_Len];
	uint16 au16PsTsetBlowTempGainY2_Tbl[CCS_nPsTsetBlowTempGain_Tbl_Len];
	uint16 au16PsTsetBlowTempGainY3_Tbl[CCS_nPsTsetBlowTempGain_Tbl_Len];
	uint16 au16PsTsetBlowTempGainY4_Tbl[CCS_nPsTsetBlowTempGain_Tbl_Len];
} CCS_tstModuleData;

typedef struct CCS_stMacro
{
	uint16 u16OatHysteresis;
	uint16 u16SetTempLowForIct;
	uint16 u16SetTempHighForIct;
	uint8 u8BlowoutTempFilterK;
	uint8 u8SetTempWeightDr;
} CCS_tstMacro;



/*************************** Group Structures ************************/

typedef struct CCS_stGroup1
{
	CCS_tstModuleInfo	stModuleInfo;
	CCS_tstModuleData	stModuleData;
	CCS_tstMacro	stMacro;
	uint8 u8AddChkSum;
	uint8  u8XorChkSum;
} CCS_tstGroup1;



/********************** LAYOUT STRUCTURE ****************************/



typedef struct
{
	CCS_tstGroup1	stGroup1;
} CCS_tstRomLayout;

extern const CCS_tstRomLayout CCS_stRomLayout;


/********************* VARIABLE ACCESS MACROS ***************************/

#define   CCS_u8Group1VariableConst		(CCS_stRomLayout.stGroup1.stModuleInfo.u8VariableConst)
#define   CCS_u8Group1ChipType		(CCS_stRomLayout.stGroup1.stModuleInfo.u8ChipType)
#define   CCS_au16Group1OatSetTempOffsetX_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16OatSetTempOffsetX_Tbl)
#define   CCS_au16Group1OatSetTempOffsetY_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16OatSetTempOffsetY_Tbl)
#define   CCS_au16Group1OatBlowTempOffsetX_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16OatBlowTempOffsetX_Tbl)
#define   CCS_au16Group1OatBlowTempOffsetY1_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16OatBlowTempOffsetY1_Tbl)
#define   CCS_au16Group1OatBlowTempOffsetY2_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16OatBlowTempOffsetY2_Tbl)
#define   CCS_au16Group1OatBlowTempOffsetY3_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16OatBlowTempOffsetY3_Tbl)
#define   CCS_au16Group1OatBlowTempOffsetY4_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16OatBlowTempOffsetY4_Tbl)
#define   CCS_au16Group1OatBlowTempSpeedX_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16OatBlowTempSpeedX_Tbl)
#define   CCS_au16Group1SiBlowTempGainX_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16SiBlowTempGainX_Tbl)
#define   CCS_au16Group1SiBlowTempGainY1_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16SiBlowTempGainY1_Tbl)
#define   CCS_au16Group1SiBlowTempGainY2_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16SiBlowTempGainY2_Tbl)
#define   CCS_au16Group1SiBlowTempGainY3_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16SiBlowTempGainY3_Tbl)
#define   CCS_au16Group1SiBlowTempGainY4_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16SiBlowTempGainY4_Tbl)
#define   CCS_au16Group1BlowTempOatX_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16BlowTempOatX_Tbl)
#define   CCS_au16Group1MmiToCcsSetTempX_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16MmiToCcsSetTempX_Tbl)
#define   CCS_au16Group1MmiToCcsSetTempY_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16MmiToCcsSetTempY_Tbl)
#define   CCS_au16Group1DrTsetBlowTempGainX_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16DrTsetBlowTempGainX_Tbl)
#define   CCS_au16Group1DrTsetBlowTempGainY1_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16DrTsetBlowTempGainY1_Tbl)
#define   CCS_au16Group1DrTsetBlowTempGainY2_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16DrTsetBlowTempGainY2_Tbl)
#define   CCS_au16Group1DrTsetBlowTempGainY3_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16DrTsetBlowTempGainY3_Tbl)
#define   CCS_au16Group1DrTsetBlowTempGainY4_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16DrTsetBlowTempGainY4_Tbl)
#define   CCS_au16Group1PsTsetBlowTempGainX_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16PsTsetBlowTempGainX_Tbl)
#define   CCS_au16Group1PsTsetBlowTempGainY1_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16PsTsetBlowTempGainY1_Tbl)
#define   CCS_au16Group1PsTsetBlowTempGainY2_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16PsTsetBlowTempGainY2_Tbl)
#define   CCS_au16Group1PsTsetBlowTempGainY3_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16PsTsetBlowTempGainY3_Tbl)
#define   CCS_au16Group1PsTsetBlowTempGainY4_Tbl		(CCS_stRomLayout.stGroup1.stModuleData.au16PsTsetBlowTempGainY4_Tbl)
#define   CCS_u16Group1OatHysteresis		(CCS_stRomLayout.stGroup1.stMacro.u16OatHysteresis)
#define   CCS_u16Group1SetTempLowForIct		(CCS_stRomLayout.stGroup1.stMacro.u16SetTempLowForIct)
#define   CCS_u16Group1SetTempHighForIct		(CCS_stRomLayout.stGroup1.stMacro.u16SetTempHighForIct)
#define   CCS_u8Group1BlowoutTempFilterK		(CCS_stRomLayout.stGroup1.stMacro.u8BlowoutTempFilterK)
#define   CCS_u8Group1SetTempWeightDr		(CCS_stRomLayout.stGroup1.stMacro.u8SetTempWeightDr)




/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*CCS_Cfg.h
******************************************************************************/