/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2018-7-4 23:03:16									 */
/**           By : uidq0760                                    */
/**        Using : BCTL_v2.9-FE-5DB.xml                         */
/**         From : D:\HVACProject\Geely\Geely_5DB_7DA_RoadTEST\FE-5DB&7DA_B1.05\ProjectCode\01_APP\BCTL\Bctl                        */
/**               (D = )                                                    */
/**************************************************************************************/
 
/******************************************************************************
Module Name : BCTL
File Name : BCTL_Cfg.h
-------------------------------------------------------------------------------
               C O P Y R I G H T
-------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.   All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 -------------------------------------------------------------------------------
  Name                                                   Company
  ---------------------          ---------------------------------------
 uidq0760                Desay SV Automotive Co., Ltd
  ---------------------          ---------------------------------------
******************************************************************************/
 
/* Module Define  */
#ifndef BCTL_CFG_H
#define BCTL_CFG_H

/* System-headerfiles */
#include "General.h"


/******************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/

#define  BCTL_nWuCdVolLimit_Len		(9U)
#define  BCTL_nOatBlwLimit_Len		(8U)
#define  BCTL_nOatSetTempOffset_Len		(8U)
#define  BCTL_nSetTempOffset_Len		(8U)
#define  BCTL_nSunOffset_Len		(7U)
#define  BCTL_nSunOffsetOatTbl_Len		(4U)
#define  BCTL_nSiOffset_Len		(11U)
#define  BCTL_nSiOffsetOatTbl_Len		(4U)
#define  BCTL_nDisInfo_Len		(29U)
#define  BCTL_nVelVolOffset_Len		(5U)
#define  BCTL_nVelVolOffsetOatTbl_Len		(4U)
#define  BCTL_nManualVolTbl_Len		(8U)
#define  BCTL_nIstpBlwLimit_Len		(15U)
#define  BCTL_nBlwVol2VltTbl_Len		(8U)


/*************************** Define Structures Arrary length ************************/

typedef struct BCTL_stWuCdLimit
{
	uint16 au16BoTempTgAtDiff[BCTL_nWuCdVolLimit_Len];
	uint16 au16WuCdVolLimit[BCTL_nWuCdVolLimit_Len];
	uint16 au16Ambient[BCTL_nOatBlwLimit_Len];
	uint16 au16OatBlwLimit[BCTL_nOatBlwLimit_Len];
} BCTL_tstWuCdLimit;

typedef struct BCTL_stAutoVol
{
	uint16 au16OatSetTempOffsetX[BCTL_nOatSetTempOffset_Len];
	uint16 au16OatSetTempOffsetY[BCTL_nOatSetTempOffset_Len];
	uint16 au16SetTempDiff[BCTL_nSetTempOffset_Len];
	uint16 au16SetTempOffset[BCTL_nSetTempOffset_Len];
	uint16 au16SunLoadX[BCTL_nSunOffset_Len];
	uint16 au16SunOffset0[BCTL_nSunOffset_Len];
	uint16 au16SunOffset1[BCTL_nSunOffset_Len];
	uint16 au16SunOffset2[BCTL_nSunOffset_Len];
	uint16 au16SunOffset3[BCTL_nSunOffset_Len];
	uint16 au16SunOffsetOatTbl[BCTL_nSunOffsetOatTbl_Len];
	uint16 au16SiOffsetX[BCTL_nSiOffset_Len];
	uint16 au16SiOffsetY0[BCTL_nSiOffset_Len];
	uint16 au16SiOffsetY1[BCTL_nSiOffset_Len];
	uint16 au16SiOffsetY2[BCTL_nSiOffset_Len];
	uint16 au16SiOffsetY3[BCTL_nSiOffset_Len];
	uint16 au16SiOffsetOatTbl[BCTL_nSiOffsetOatTbl_Len];
	uint16 au16TrgVolX[BCTL_nDisInfo_Len];
	uint16 au16DisInfoInc[BCTL_nDisInfo_Len];
	uint16 au16DisInfoDec[BCTL_nDisInfo_Len];
	uint16 au16VelX[BCTL_nVelVolOffset_Len];
	uint16 au16VelVolOffset0[BCTL_nVelVolOffset_Len];
	uint16 au16VelVolOffset1[BCTL_nVelVolOffset_Len];
	uint16 au16VelVolOffset2[BCTL_nVelVolOffset_Len];
	uint16 au16VelVolOffset3[BCTL_nVelVolOffset_Len];
	uint16 au16VelVolOffsetOatTbl[BCTL_nVelVolOffsetOatTbl_Len];
} BCTL_tstAutoVol;

typedef struct BCTL_stManualVol
{
	uint16 au16ManualVolTbl[BCTL_nManualVolTbl_Len];
} BCTL_tstManualVol;

typedef struct BCTL_stISTP
{
	uint16 au16IstpBlwLimitOatX[BCTL_nIstpBlwLimit_Len];
	uint16 au16IstpBlwLimitY[BCTL_nIstpBlwLimit_Len];
} BCTL_tstISTP;

typedef struct BCTL_stVol2Vlt
{
	uint16 au16BlwVol2VltTblX[BCTL_nBlwVol2VltTbl_Len];
	uint16 au16BlwVol2VltTblNorFreY[BCTL_nBlwVol2VltTbl_Len];
	uint16 au16BlwVol2VltTblNorRecY[BCTL_nBlwVol2VltTbl_Len];
	uint16 au16BlwVol2VltTblIsFreY[BCTL_nBlwVol2VltTbl_Len];
	uint16 au16BlwVol2VltTblIsRecY[BCTL_nBlwVol2VltTbl_Len];
} BCTL_tstVol2Vlt;



/*************************** Group Structures ************************/

typedef struct BCTL_stRom
{
	BCTL_tstWuCdLimit	stWuCdLimit;
	BCTL_tstAutoVol	stAutoVol;
	BCTL_tstManualVol	stManualVol;
	BCTL_tstISTP	stISTP;
	BCTL_tstVol2Vlt	stVol2Vlt;
	uint8 u8AddChkSum;
	uint8  u8XorChkSum;
} BCTL_tstRom;



/********************** LAYOUT STRUCTURE ****************************/



typedef struct
{
	BCTL_tstRom	stRom;
} BCTL_tstRomLayout;

extern const BCTL_tstRomLayout BCTL_stRomLayout;


/********************* VARIABLE ACCESS MACROS ***************************/

#define   BCTL_au16RomBoTempTgAtDiff		(BCTL_stRomLayout.stRom.stWuCdLimit.au16BoTempTgAtDiff)
#define   BCTL_au16RomWuCdVolLimit		(BCTL_stRomLayout.stRom.stWuCdLimit.au16WuCdVolLimit)
#define   BCTL_au16RomAmbient		(BCTL_stRomLayout.stRom.stWuCdLimit.au16Ambient)
#define   BCTL_au16RomOatBlwLimit		(BCTL_stRomLayout.stRom.stWuCdLimit.au16OatBlwLimit)
#define   BCTL_au16RomOatSetTempOffsetX		(BCTL_stRomLayout.stRom.stAutoVol.au16OatSetTempOffsetX)
#define   BCTL_au16RomOatSetTempOffsetY		(BCTL_stRomLayout.stRom.stAutoVol.au16OatSetTempOffsetY)
#define   BCTL_au16RomSetTempDiff		(BCTL_stRomLayout.stRom.stAutoVol.au16SetTempDiff)
#define   BCTL_au16RomSetTempOffset		(BCTL_stRomLayout.stRom.stAutoVol.au16SetTempOffset)
#define   BCTL_au16RomSunLoadX		(BCTL_stRomLayout.stRom.stAutoVol.au16SunLoadX)
#define   BCTL_au16RomSunOffset0		(BCTL_stRomLayout.stRom.stAutoVol.au16SunOffset0)
#define   BCTL_au16RomSunOffset1		(BCTL_stRomLayout.stRom.stAutoVol.au16SunOffset1)
#define   BCTL_au16RomSunOffset2		(BCTL_stRomLayout.stRom.stAutoVol.au16SunOffset2)
#define   BCTL_au16RomSunOffset3		(BCTL_stRomLayout.stRom.stAutoVol.au16SunOffset3)
#define   BCTL_au16RomSunOffsetOatTbl		(BCTL_stRomLayout.stRom.stAutoVol.au16SunOffsetOatTbl)
#define   BCTL_au16RomSiOffsetX		(BCTL_stRomLayout.stRom.stAutoVol.au16SiOffsetX)
#define   BCTL_au16RomSiOffsetY0		(BCTL_stRomLayout.stRom.stAutoVol.au16SiOffsetY0)
#define   BCTL_au16RomSiOffsetY1		(BCTL_stRomLayout.stRom.stAutoVol.au16SiOffsetY1)
#define   BCTL_au16RomSiOffsetY2		(BCTL_stRomLayout.stRom.stAutoVol.au16SiOffsetY2)
#define   BCTL_au16RomSiOffsetY3		(BCTL_stRomLayout.stRom.stAutoVol.au16SiOffsetY3)
#define   BCTL_au16RomSiOffsetOatTbl		(BCTL_stRomLayout.stRom.stAutoVol.au16SiOffsetOatTbl)
#define   BCTL_au16RomTrgVolX		(BCTL_stRomLayout.stRom.stAutoVol.au16TrgVolX)
#define   BCTL_au16RomDisInfoInc		(BCTL_stRomLayout.stRom.stAutoVol.au16DisInfoInc)
#define   BCTL_au16RomDisInfoDec		(BCTL_stRomLayout.stRom.stAutoVol.au16DisInfoDec)
#define   BCTL_au16RomVelX		(BCTL_stRomLayout.stRom.stAutoVol.au16VelX)
#define   BCTL_au16RomVelVolOffset0		(BCTL_stRomLayout.stRom.stAutoVol.au16VelVolOffset0)
#define   BCTL_au16RomVelVolOffset1		(BCTL_stRomLayout.stRom.stAutoVol.au16VelVolOffset1)
#define   BCTL_au16RomVelVolOffset2		(BCTL_stRomLayout.stRom.stAutoVol.au16VelVolOffset2)
#define   BCTL_au16RomVelVolOffset3		(BCTL_stRomLayout.stRom.stAutoVol.au16VelVolOffset3)
#define   BCTL_au16RomVelVolOffsetOatTbl		(BCTL_stRomLayout.stRom.stAutoVol.au16VelVolOffsetOatTbl)
#define   BCTL_au16RomManualVolTbl		(BCTL_stRomLayout.stRom.stManualVol.au16ManualVolTbl)
#define   BCTL_au16RomIstpBlwLimitOatX		(BCTL_stRomLayout.stRom.stISTP.au16IstpBlwLimitOatX)
#define   BCTL_au16RomIstpBlwLimitY		(BCTL_stRomLayout.stRom.stISTP.au16IstpBlwLimitY)
#define   BCTL_au16RomBlwVol2VltTblX		(BCTL_stRomLayout.stRom.stVol2Vlt.au16BlwVol2VltTblX)
#define   BCTL_au16RomBlwVol2VltTblNorFreY		(BCTL_stRomLayout.stRom.stVol2Vlt.au16BlwVol2VltTblNorFreY)
#define   BCTL_au16RomBlwVol2VltTblNorRecY		(BCTL_stRomLayout.stRom.stVol2Vlt.au16BlwVol2VltTblNorRecY)
#define   BCTL_au16RomBlwVol2VltTblIsFreY		(BCTL_stRomLayout.stRom.stVol2Vlt.au16BlwVol2VltTblIsFreY)
#define   BCTL_au16RomBlwVol2VltTblIsRecY		(BCTL_stRomLayout.stRom.stVol2Vlt.au16BlwVol2VltTblIsRecY)




/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*BCTL_Cfg.h
******************************************************************************/