/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2016/3/3  18:46:52                                       */
/**           By : uidp4501                                                 */
/**        Using : Ion_Cfg.xls                                              */
/**         From : D:\HVACProject\Geely\KC-2\ATC\01_Application\02_Sources\01_CC\01_APP\ION*/
/**               (D = )                                                    */
/**************************************************************************************/
 
/******************************************************************************
Module Name : ION
File Name : ION_Cfg.h
-------------------------------------------------------------------------------
               C O P Y R I G H T
-------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.   All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 -------------------------------------------------------------------------------
  Name                                                   Company
  ---------------------          ---------------------------------------
 uidp4501                         Desay SV Automotive Co., Ltd
  ---------------------          ---------------------------------------
******************************************************************************/
 
/* Module Define  */
#ifndef ION_CFG_H
#define ION_CFG_H

/* System-headerfiles */
#include "General.h"


/******************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/


/*************************** Define Structures Arrary length ************************/

typedef struct ION_stIonInfo
{
   uint8    u8VariableConst;
   uint8    u8ChipType;
   uint8    u8VCFillByte2;
   uint8    u8VCFillByte3;
   uint8    u8VCFillByte4;
   uint8    u8VCFillByte5;
   uint8    u8VCFillByte6;
   uint8    u8VCFillByte7;
   uint8    u8VCFillByte8;
   uint8    u8VCFillByte9;
   uint8    u8VCFillByte10;
   uint8    u8VCFillByte11;
   uint8    u8VCFillByte12;
   uint8    u8VCFillByte13;
} ION_tstIonInfo;

/*************************** Group Structures ************************/
typedef struct ION_stGroup1
{
   ION_tstIonInfo  stIonInfo;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} ION_tstGroup1;

/********************** LAYOUT STRUCTURE ****************************/
typedef struct 
{
   ION_tstGroup1  stGroup1;
} ION_tstLayout;


extern  ION_tstLayout ION_stLayout;

/********************* VARIABLE ACCESS MACROS ***************************/
#define   ION_u8Group1VariableConst               (ION_stLayout.stGroup1.stIonInfo.u8VariableConst)
#define   ION_u8Group1ChipType                    (ION_stLayout.stGroup1.stIonInfo.u8ChipType)
#define   ION_u8Group1VCFillByte2                 (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte2)
#define   ION_u8Group1VCFillByte3                 (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte3)
#define   ION_u8Group1VCFillByte4                 (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte4)
#define   ION_u8Group1VCFillByte5                 (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte5)
#define   ION_u8Group1VCFillByte6                 (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte6)
#define   ION_u8Group1VCFillByte7                 (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte7)
#define   ION_u8Group1VCFillByte8                 (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte8)
#define   ION_u8Group1VCFillByte9                 (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte9)
#define   ION_u8Group1VCFillByte10                (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte10)
#define   ION_u8Group1VCFillByte11                (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte11)
#define   ION_u8Group1VCFillByte12                (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte12)
#define   ION_u8Group1VCFillByte13                (ION_stLayout.stGroup1.stIonInfo.u8VCFillByte13)
/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*ION_Cfg.h
******************************************************************************/
