/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2016/11/10 15:12:27									 */
/**           By : uidp4501                                    */
/**        Using : BCTLDRV.xml                         */
/**         From : D:\HVACProject\Geely\FE-5A7A\ATC\01_Application\02_Sources\01_CC\01_APP\BCTL\BctlDrv                        */
/**               (D = )                                                    */
/**************************************************************************************/
 
/******************************************************************************
Module Name : BCTLDRV
File Name : BCTLDRV_Cfg.h
-------------------------------------------------------------------------------
               C O P Y R I G H T
-------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.   All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 -------------------------------------------------------------------------------
  Name                                                   Company
  ---------------------          ---------------------------------------
 uidp4501                Desay SV Automotive Co., Ltd
  ---------------------          ---------------------------------------
******************************************************************************/
 
/* Module Define  */
#ifndef BCTLDRV_CFG_H
#define BCTLDRV_CFG_H

/* System-headerfiles */
#include "General.h"


/******************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/

#define  BCTLDRV_nVolt2Pwm_Len		(9U)
#define  BCTLDRV_nFbVolt_Len		(9U)


/*************************** Define Structures Arrary length ************************/

typedef struct BCTLDRV_stVoltage2PwmDuty
{
	uint16 au16TrgVolt[BCTLDRV_nVolt2Pwm_Len];
	uint16 au16PwmDuty[BCTLDRV_nVolt2Pwm_Len];
} BCTLDRV_tstVoltage2PwmDuty;

typedef struct BCTLDRV_stFeedbcakVoltage
{
	uint16 au16FbDigital[BCTLDRV_nFbVolt_Len];
	uint16 au16FbVolt[BCTLDRV_nFbVolt_Len];
} BCTLDRV_tstFeedbcakVoltage;



/*************************** Group Structures ************************/

typedef struct BCTLDRV_stRom
{
	BCTLDRV_tstVoltage2PwmDuty	stVoltage2PwmDuty;
	BCTLDRV_tstFeedbcakVoltage	stFeedbcakVoltage;
	uint8 u8AddChkSum;
	uint8  u8XorChkSum;
} BCTLDRV_tstRom;



/********************** LAYOUT STRUCTURE ****************************/



typedef struct
{
	BCTLDRV_tstRom	stRom;
} BCTLDRV_tstRomLayout;

extern const BCTLDRV_tstRomLayout BCTLDRV_stRomLayout;


/********************* VARIABLE ACCESS MACROS ***************************/

#define   BCTLDRV_au16RomTrgVolt		(BCTLDRV_stRomLayout.stRom.stVoltage2PwmDuty.au16TrgVolt)
#define   BCTLDRV_au16RomPwmDuty		(BCTLDRV_stRomLayout.stRom.stVoltage2PwmDuty.au16PwmDuty)
#define   BCTLDRV_au16RomFbDigital		(BCTLDRV_stRomLayout.stRom.stFeedbcakVoltage.au16FbDigital)
#define   BCTLDRV_au16RomFbVolt		(BCTLDRV_stRomLayout.stRom.stFeedbcakVoltage.au16FbVolt)




/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*BCTLDRV_Cfg.h
******************************************************************************/

