/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2016/11/10 15:12:27                                      */
/**           By : uidp4501                                      */
/**        Using : BCTLDRV.xml                         */
/**         From : D:\HVACProject\Geely\FE-5A7A\ATC\01_Application\02_Sources\01_CC\01_APP\BCTL\BctlDrv                             */
/**               (D = )                                                    */
/**************************************************************************************/

/**************************************************************************************
 Module Name : BCTLDRV
 File Name : BCTLDRV_Cfg.c
--------------------------------------------------------------------------------------
               C O P Y R I G H T
--------------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.    All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 ------------------------------------------------------------------------------------
  Name                                          Company
  -----------------------------          ---------------------------------------
 uidp4501                              Desay SV Automotive Co., Ltd
  -----------------------------          ---------------------------------------
***************************************************************************************/
/*Module Define*/
#define BCTLDRV_CFG

/*Header file */
#include "BCTLDRV_Cfg.h"

/***************************************************************************************
*MODULE GLOBAL CONFIGURATION CONSTANTS
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
***************************************************************************************/



const BCTLDRV_tstRomLayout BCTLDRV_stRomLayout = {
	{  /*----------------------- Rom ---------------------------------------*/
		{  /* Voltage2PwmDuty */
			{ 0x0U,0x198U,0x230U,0x2c4U,0x352U,0x3eaU,0x47cU,0x5aaU,0x5faU },				/* au16TrgVolt */
			{ 0x0U,0xecU,0x150U,0x1b8U,0x21cU,0x280U,0x2e8U,0x3b0U,0x3e8U },				/* au16PwmDuty */
		},
		{  /* FeedbcakVoltage */
			{ 0x14U,0xecU,0x150U,0x1b8U,0x21cU,0x280U,0x2e8U,0x3b0U,0x3e8U },				/* au16FbDigital */
			{ 0x0U,0x198U,0x230U,0x2c4U,0x352U,0x3eaU,0x47cU,0x5aaU,0x5f9U },				/* au16FbVolt */
		},
		0x52U,				 /* u8AddChkSum */
		0xe8U,				 /* u8XorChkSum */
	},
};




/**********************************End Of File*****************************************
*************************BCTLDRV_CFG_C ****************************
***************************************************************************************/
