/********************* MODULE STRUCTURE DEFINITIONS *************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 09/11/2014  14:57:28                                     */
/**           By : test                                                     */
/**        Using : Knob_Cfg_Template_Release_A01.xls                        */
/**         From : D:\uidp4036\Desktop\Sources\Knob                         */
/**               (D = )                                                    */
/****************************************************************************/
/*****************************************************************************
* FILE DECLARATION
******************************************************************************/
#ifndef KNOB_CFG_H
#define KNOB_CFG_H
/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
******************************************************************************/
/* System-headerfiles */




/*****************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/
#define   KNOB_TWO_LINE_HALF_PHASE  0
#define   KNOB_TWO_LINE_FULL_PHASE  1
#define   KNOB_THREE_LINE           2
#define   KNOB_DETECTOR             3
#define   KnobNum                   2

#define  KNOBType           KNOB_TWO_LINE_FULL_PHASE
#define  KNOB_TWO_LINE_FULL_PHASE_HIGH_START  




 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*KNOB_Cfg.h
******************************************************************************/
