/************************** DEFAULTS ************************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 09/11/2014  14:57:29                                     */
/**           By : test                                                     */
/**        Using : Knob_Cfg_Template_Release_A01.xls                        */
/**         From : D:\uidp4036\Desktop\Sources\Knob                         */
/**               (D = )                                                    */
/****************************************************************************/

/*****************************************************************************
* FILE DECLARATION
*****************************************************************************/

#define KNOB_CFG

/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
*****************************************************************************/
#include "KNOB_Cfg.h"
#include "Knob_type.h"
#include "KNOB_Interface.h"
#include "RTE_internal.h"


/*****************************************************************************
* MODULE GLOBAL CONFIGURATION CONSTANTS
*
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
*****************************************************************************/
/*****************************************************************************
		   CW:
		       ------		   ------		  
		   A:	     |		  |	     |		  
					 |________|      |________ 

				  11->01-> 00-> 10->  11 
		   B:	   ------		   ------		  
			    	     |		  |	     |		  
						 |________|      |________ 


		   CCW:


		   A:      ------		   ------		  
			    	     |		  |	      |		  
						 |________|       |________ 
				  11->10-> 00-> 01->11   		
		        ------		    ------	  
		   B:	      |		   |	   |		  
					  |________|       |________ 
			

*****************************************************************************/

KNOB_tstProperty Knob_stProperty[KnobNum]=
{
    /*KnobName, FilterTime, MaxTransitionTime, fpKnobGetStatusA,fpKnobGetStatusB*/
    KnobDefineTwoLine(TempLKnob,1u,3000u,Rte_Call_IoHwPortRead_IoHwReadPort_ReadPort_KnobTempR2_Read,Rte_Call_IoHwPortRead_IoHwReadPort_ReadPort_KnobTempR1_Read),
    KnobDefineTwoLine(TempRKnob,1u,3000u,Rte_Call_IoHwPortRead_IoHwReadPort_ReadPort_KnobTempL2_Read,Rte_Call_IoHwPortRead_IoHwReadPort_ReadPort_KnobTempL1_Read),
};



