/**************************************************************************************/
/*------------------------------------------------------------------------------------
              Automatically Generated File,do not edit this file manually!
-------------------------------------------------------------------------------------*/
/** Generated On : 2018-5-30  15:54:06                                      */
/**           By : uidp4501                                                 */
/**        Using : Aqs_Cfg_1.1.xls                                          */
/**         From : D:\HVACProject\Geely\FE-5DB&7DA\ProjectCode\01_APP\AQS   */
/**               (D = )                                                    */
/**************************************************************************************/

/**************************************************************************************
 Module Name : AQS
 File Name : AQS_Cfg.c
--------------------------------------------------------------------------------------
               C O P Y R I G H T
--------------------------------------------------------------------------------------
 Copyright (c) 2015 Huizhou Desay SV Automotive Co., Ltd.    All rights reserved.

 This software is copyright protected and proprietary to Desay SV Automotive Co., Ltd.
 Desay SV Automotive Co., Ltd grants to you only those rights as set out in the
 license conditions. All other rights remain with Desay SV Automotive Co., Ltd.

 REMOVAL OF THESE COMMENTS IS A VIOLATION OF THE LICENSE AGREEMENT.
 -------------------------------------------------------------------------------------
               A U T H O R   I D E N T I T Y
 ------------------------------------------------------------------------------------
  Name                                          Company
  -----------------------------          ---------------------------------------
 uidp4501                              Desay SV Automotive Co., Ltd
  -----------------------------          ---------------------------------------
***************************************************************************************/
/*Module Define*/
#define AQS_CFG

/*Header file */
#include "AQS_Cfg.h"

/***************************************************************************************
*MODULE GLOBAL CONFIGURATION CONSTANTS
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
***************************************************************************************/




 const AQS_tstRomLayout AQS_stRomLayout = {

   {  /*----------------------- Group1 ---------------------------------------*/

      {  /* DimInfo */
         0x1U,                                                    /* u8VariableConst */
         0x0U,                                                    /* u8ChipType */
         0x64U,                                                   /* u8AirFilterTime */
         0xFFU,                                                   /* u8FpDataFill1 */
         { 0x0000U,0x001EU,0x003CU,0x0050U },                     /* au16AqsRecSwitchPoint_X */
         { 0x0023U,0x0037U,0x0041U,0x0055U },                     /* au16AqsRecSwitchPoint_Y */
         { 0x0000U,0x001EU,0x003CU,0x0050U },                     /* au16AqsFreshSwitchPoint_X */
         { 0x0005U,0x0019U,0x0023U,0x0037U },                     /* au16AqsFreshSwitchPoint_Y */
         0xFFU,                                                   /* u8FpDataFill2 */
         0xFFU                                                    /* u8FpDataFill3 */
      },
      0xE1U,                                                      /* u8AddChkSum */
      0x93U                                                       /* u8XorChkSum */
   }
};
