/************************** DEFAULTS ************************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 2016/10/11  15:27:49                                     */
/**           By : Client Service Account (hzh1_csa06)                      */
/**        Using : Ict_Cfg.xlsm                                             */
/**         From : D:\HVACproject\Geely\Geely KC-2HP\ATC\01_Application\02_Sources\01_CC\01_APP\ICT*/
/**               (D = )                                                    */
/****************************************************************************/

/*****************************************************************************
* FILE DECLARATION
*****************************************************************************/

#define ICT_CFG

/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
*****************************************************************************/
#include "ICT.h"


/*****************************************************************************
* MODULE GLOBAL CONFIGURATION CONSTANTS
*
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
*****************************************************************************/




const ICT_tstRomLayout ICT_stRomLayout = {

   {  /*----------------------- GroupIct1 ---------------------------------------*/

      {  /* Info1 */
         0x1U,                                                    /* u8VariableConst */
         0x0U,                                                    /* u8ChipType */
         0xFFU,                                                   /* u8HeaderFillByte1 */
         0xFFU                                                    /* u8HeaderFillByte2 */
      },

      {  /* Data1 */
         { 0x0024U,0x0063U,0x00C7U,0x00ECU,0x0116U,0x0147U,0x01F7U,0x0326U,0x039AU },  /* au16SensorValueX */
         { 0x04B0U,0x0384U,0x02BCU,0x028AU,0x0258U,0x0226U,0x0190U,0x0096U,0x0000U }  /* au16SensorValueY */
      },
      0x7BU,                                                      /* u8AddChkSum */
      0xBU                                                        /* u8XorChkSum */
   },

   {  /*----------------------- GroupIct2 ---------------------------------------*/

      {  /* Info2 */
         0x1U,                                                    /* u8VariableConst */
         0xFFU                                                    /* u8HeaderFillByte1 */
      },

      {  /* Data2 */
         { 0x0000U,0x0001U,0x0002U,0x0003U,0x0004U,0x0005U,0x0006U },  /* au16StaticOffsetTbl_X */
         { 0x021CU,0x021CU,0x021CU,0x021CU,0x021CU,0x021CU,0x021CU },  /* au16StaticOffsetTbl_Y0 */
         { 0x023AU,0x023AU,0x023AU,0x023AU,0x023AU,0x023AU,0x023AU },  /* au16StaticOffsetTbl_Y1 */
         { 0x0280U,0x0280U,0x0280U,0x0280U,0x0280U,0x0280U,0x0280U },  /* au16StaticOffsetTbl_Y2 */
         { 0x028AU,0x028AU,0x028AU,0x028AU,0x028AU,0x028AU,0x028AU },  /* au16StaticOffsetTbl_Y3 */
         { 0x00FAU,0x01C2U,0x028AU,0x0320U },                     /* au16StaticOffsetAmbientTbl */
         { 0x00C8U,0x012CU,0x0190U,0x01F4U,0x0258U,0x02BCU,0x0320U },  /* au16DynamicMaxTbl_X */
         { 0x0064U,0x0064U,0x0064U,0x0064U,0x0064U,0x0064U,0x0064U },  /* au16DynamicMaxTbl_Y */
         { 0x00C8U,0x012CU,0x0190U,0x01F4U,0x0258U,0x02BCU,0x0320U },  /* au16DynamicFactorTbl_X */
         { 0x0100U,0x01B2U,0x024CU,0x0328U,0x02ADU,0x0229U,0x0153U },  /* au16DynamicFactorTbl_Y */
         { 0x0000U,0x0005U,0x0014U,0x001EU,0x0032U },             /* au16DampingFactorX */
         { 0x0007U,0x0007U,0x0004U,0x0002U,0x0001U }              /* au16DampingFactorY */
      },
      0xA5U,                                                      /* u8AddChkSum */
      0x19U                                                       /* u8XorChkSum */
   }
};
