/********************* MODULE STRUCTURE DEFINITIONS *************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 2016/10/11  15:27:48                                     */
/**           By : Client Service Account (hzh1_csa06)                      */
/**        Using : Ict_Cfg.xlsm                                             */
/**         From : D:\HVACproject\Geely\Geely KC-2HP\ATC\01_Application\02_Sources\01_CC\01_APP\ICT*/
/**               (D = )                                                    */
/****************************************************************************/
/*****************************************************************************
* FILE DECLARATION
******************************************************************************/
#ifndef ICT_CFG_H
#define ICT_CFG_H
/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
******************************************************************************/
/* System-headerfiles */
#include "General.h"


/*****************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/


#define  ICT_nSensorValue_Len    (9U)
#define  ICT_nStaticOffsetTbl_Len    (7U)
#define  ICT_nAmbientTbl_Len    (4U)
#define  ICT_nDynamicMaxTbl_Len    (7U)
#define  ICT_nDynamicFactorTbl_Len    (7U)
#define  ICT_nDampingFactor_len    (5U)

/*************************** Define Structures Arrary length ************************/

typedef const struct ICT_stInfo1
{
   const uint8    u8VariableConst;
   const uint8    u8ChipType;
   const uint8    u8HeaderFillByte1;
   const uint8    u8HeaderFillByte2;
} ICT_tstInfo1;

typedef const struct ICT_stData1
{
   const uint16   au16SensorValueX [ ICT_nSensorValue_Len ];
   const uint16   au16SensorValueY [ ICT_nSensorValue_Len ];
} ICT_tstData1;

typedef const struct ICT_stInfo2
{
   const uint8    u8VariableConst;
   const uint8    u8HeaderFillByte1;
} ICT_tstInfo2;

typedef const struct ICT_stData2
{
   const uint16   au16StaticOffsetTbl_X [ ICT_nStaticOffsetTbl_Len ];
   const uint16   au16StaticOffsetTbl_Y0 [ ICT_nStaticOffsetTbl_Len ];
   const uint16   au16StaticOffsetTbl_Y1 [ ICT_nStaticOffsetTbl_Len ];
   const uint16   au16StaticOffsetTbl_Y2 [ ICT_nStaticOffsetTbl_Len ];
   const uint16   au16StaticOffsetTbl_Y3 [ ICT_nStaticOffsetTbl_Len ];
   const uint16   au16StaticOffsetAmbientTbl [ ICT_nAmbientTbl_Len ];
   const uint16   au16DynamicMaxTbl_X [ ICT_nDynamicMaxTbl_Len ];
   const uint16   au16DynamicMaxTbl_Y [ ICT_nDynamicMaxTbl_Len ];
   const uint16   au16DynamicFactorTbl_X [ ICT_nDynamicFactorTbl_Len ];
   const uint16   au16DynamicFactorTbl_Y [ ICT_nDynamicFactorTbl_Len ];
   const uint16   au16DampingFactorX [ ICT_nDampingFactor_len ];
   const uint16   au16DampingFactorY [ ICT_nDampingFactor_len ];
} ICT_tstData2;

/*************************** Group Structures ************************/
typedef const struct ICT_stGroupIct1
{
   ICT_tstInfo1  stInfo1;
   ICT_tstData1  stData1;
   const uint8  u8AddChkSum;
   const uint8  u8XorChkSum;
} ICT_tstGroupIct1;

typedef const struct ICT_stGroupIct2
{
   ICT_tstInfo2  stInfo2;
   ICT_tstData2  stData2;
   const uint8  u8AddChkSum;
   const uint8  u8XorChkSum;
} ICT_tstGroupIct2;

/********************** LAYOUT STRUCTURE ****************************/

typedef const struct 
{
   ICT_tstGroupIct1  stGroupIct1;
   ICT_tstGroupIct2  stGroupIct2;
} ICT_tstRomLayout;

extern const ICT_tstRomLayout ICT_stRomLayout;

/********************* VARIABLE ACCESS MACROS ***************************/
#define   ICT_u8GroupIct1VariableConst            (ICT_stRomLayout.stGroupIct1.stInfo1.u8VariableConst)
#define   ICT_u8GroupIct1ChipType                 (ICT_stRomLayout.stGroupIct1.stInfo1.u8ChipType)
#define   ICT_u8GroupIct1HeaderFillByte1          (ICT_stRomLayout.stGroupIct1.stInfo1.u8HeaderFillByte1)
#define   ICT_u8GroupIct1HeaderFillByte2          (ICT_stRomLayout.stGroupIct1.stInfo1.u8HeaderFillByte2)
#define   ICT_au16GroupIct1SensorValueX           (ICT_stRomLayout.stGroupIct1.stData1.au16SensorValueX)
#define   ICT_au16GroupIct1SensorValueY           (ICT_stRomLayout.stGroupIct1.stData1.au16SensorValueY)
#define   ICT_u8GroupIct2VariableConst            (ICT_stRomLayout.stGroupIct2.stInfo2.u8VariableConst)
#define   ICT_u8GroupIct2HeaderFillByte1          (ICT_stRomLayout.stGroupIct2.stInfo2.u8HeaderFillByte1)
#define   ICT_au16GroupIct2StaticOffsetTbl_X          (ICT_stRomLayout.stGroupIct2.stData2.au16StaticOffsetTbl_X)
#define   ICT_au16GroupIct2StaticOffsetTbl_Y0          (ICT_stRomLayout.stGroupIct2.stData2.au16StaticOffsetTbl_Y0)
#define   ICT_au16GroupIct2StaticOffsetTbl_Y1          (ICT_stRomLayout.stGroupIct2.stData2.au16StaticOffsetTbl_Y1)
#define   ICT_au16GroupIct2StaticOffsetTbl_Y2          (ICT_stRomLayout.stGroupIct2.stData2.au16StaticOffsetTbl_Y2)
#define   ICT_au16GroupIct2StaticOffsetTbl_Y3          (ICT_stRomLayout.stGroupIct2.stData2.au16StaticOffsetTbl_Y3)
#define   ICT_au16GroupIct2StaticOffsetAmbientTbl          (ICT_stRomLayout.stGroupIct2.stData2.au16StaticOffsetAmbientTbl)
#define   ICT_au16GroupIct2DynamicMaxTbl_X          (ICT_stRomLayout.stGroupIct2.stData2.au16DynamicMaxTbl_X)
#define   ICT_au16GroupIct2DynamicMaxTbl_Y          (ICT_stRomLayout.stGroupIct2.stData2.au16DynamicMaxTbl_Y)
#define   ICT_au16GroupIct2DynamicFactorTbl_X          (ICT_stRomLayout.stGroupIct2.stData2.au16DynamicFactorTbl_X)
#define   ICT_au16GroupIct2DynamicFactorTbl_Y          (ICT_stRomLayout.stGroupIct2.stData2.au16DynamicFactorTbl_Y)
#define   ICT_au16GroupIct2DampingFactorX          (ICT_stRomLayout.stGroupIct2.stData2.au16DampingFactorX)
#define   ICT_au16GroupIct2DampingFactorY          (ICT_stRomLayout.stGroupIct2.stData2.au16DampingFactorY)
#define   ICT_nSensorDefault                      (650U)    /**/
#define   ICT_nDynOffsetZeroPoint                 (200U)    /**/
#define   ICT_nDynamicOffsetTimeCircle            (16U)    /**/
#define   ICT_nDynamicFactorRes                   (1000U)    /**/
#define   ICT_nReserve11                          (0U)    /**/
#define   ICT_nSensorSgErrorMask                  (1U)    /**/
#define   ICT_nSensorSpErrorMask                  (2U)    /**/
#define   ICT_nStaticOffsetInputErrorMask          (4U)    /**/
#define   ICT_nDynamicOffsetInputErrorMask          (8U)    /**/
#define   ICT_nReserve21                          (16U)    /**/
#define   ICT_nReserve22                          (32U)    /**/
#define   ICT_nReserve23                          (64U)    /**/
#define   ICT_nReserve24                          (128U)    /**/
#define   ICT_nReserve25                          (256U)    /**/
#define   ICT_nReserve26                          (512U)    /**/
#define   ICT_nReserve27                          (1024U)    /**/
#define   ICT_nReserve28                          (2048U)    /**/
#define   ICT_nOatStaticOffsetStep                (3U)    /**/
#define   ICT_nStaticTimeBasePar                  (10U)    /**/
#define   ICT_nReserve32                          (0U)    /**/
#define   ICT_nReserve33                          (1U)    /**/
#define   ICT_nReserve34                          (2U)    /**/
#define   ICT_nReserve35                          (3U)    /**/
#define   ICT_nReserve36                          (1U)    /**/
#define   ICT_nReserve37                          (9U)    /**/
#define   ICT_nReserve38                          (20U)    /**/
/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*ICT_Cfg.h
******************************************************************************/
