/********************* MODULE STRUCTURE DEFINITIONS *************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 2017-03-30  0:00                                         */
/**           By : uidp3720                                                 */
/** EEPROM Manager Version : 1.5.4.29526                                    */
/** EEPROM Version : C2.4                                                   */
/**         From : D:\HVACProject\Geely\FE-3HP\ATC\01_Application\02_Sources\01_CC\01_APP\EED*/
/****************************************************************************/
 
/*************************** BIT STRUCTURES ************************/
typedef struct 
{
   uint8 SeatHeatersModule:1;
   uint8 TemperatureUnit:1;
   uint8 DefrostForcesBlowertoMax:1;
   uint8 MixedAirDisModeSafety:1;
   uint8 MixedAirAdaptiveControl:1;
   uint8 CompressorControlMode:1;
   uint8 DriverSide:1;
} EED_tstSystem_BitDefine_Byte_1;
 
/*************************** MODULE STRUCTURES ************************/
typedef struct 
{
   uint8    u8EEP_Group_Info;
   uint8    u8EEP_Version_Major;
   uint8    u8EEP_Version_Minor;
   uint8    u8SW_Version_Major;
   uint8    u8SW_Version_Minor;
   uint8    u8DevelopModeMsgEn;
   uint8    u8DevelopModeStstEn;
   uint8    u8FillerByte_System_Ext1;
} EED_tstSystem_EXT;
 
typedef struct 
{
   uint8   au8MMIBuffer_Tbl [ EED_nMMIBuffer_Tbl_Len ];
} EED_tstMMI;
 
typedef struct 
{
   uint8   au8OATBuffer_Tbl [ EED_nOATBuffer_Tbl_Len ];
} EED_tstOAT;
 
typedef struct 
{
   uint8   au8DIAGBuffer_Tbl [ EED_nDIAGBuffer_Tbl_Len ];
} EED_tstDIAG;
 
typedef struct 
{
   uint8   au8DTCBuffer_Tbl [ EED_nDTCBuffer_Tbl_Len ];
} EED_tstDTC;
 
typedef struct 
{
   uint8   au8PTSBuffer_Tbl [ EED_nPTSBuffer_Tbl_Len ];
} EED_tstPTS;
 
typedef struct 
{
   uint8   au8FPBuffer_Tbl [ EED_nFPBuffer_Tbl_Len ];
} EED_tstFP;
 
typedef struct 
{
   EED_tstSystem_BitDefine_Byte_1    bi8System_BitDefine_Byte_1;
   uint8    u8FillerByte_System1;
} EED_tstSystem;
 
/*************************** GROUP STRUCTURES ************************/
typedef struct 
{
   EED_tstSystem_EXT  stSystem_EXT;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} EED_tstGROUP1;
 
typedef struct 
{
   EED_tstMMI  stMMI;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} EED_tstGROUP2;
 
typedef struct 
{
   EED_tstOAT  stOAT;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} EED_tstGROUP3;
 
typedef struct 
{
   EED_tstDIAG  stDIAG;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} EED_tstGROUP4;
 
typedef struct 
{
   EED_tstDTC  stDTC;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} EED_tstGROUP5;
 
typedef struct 
{
   EED_tstPTS  stPTS;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} EED_tstGROUP6;
 
typedef struct 
{
   EED_tstFP  stFP;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} EED_tstGROUP7;
 
typedef struct 
{
   EED_tstSystem  stSystem;
   uint8  u8AddChkSum;
   uint8  u8XorChkSum;
} EED_tstGROUP8;
 
/********************** EED LAYOUT STRUCTURE ****************************/
typedef struct 
{
   EED_tstGROUP1  stGROUP1;
   EED_tstGROUP2  stGROUP2;
   EED_tstGROUP3  stGROUP3;
   EED_tstGROUP4  stGROUP4;
   EED_tstGROUP5  stGROUP5;
   EED_tstGROUP6  stGROUP6;
   EED_tstGROUP7  stGROUP7;
   EED_tstGROUP8  stGROUP8;
} EED_tstLayout;
 
typedef struct 
{
   uint8 au8Unused1 [ 878U ];
} EED_tstUnprotected;
