/********************* EED VARIABLE ACCESS MACROS ***************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 2017-03-30  0:00                                         */
/**           By : uidp3720                                                 */
/** EEPROM Manager Version : 1.5.4.29526                                    */
/** EEPROM Version : C2.4                                                   */
/**         From : D:\HVACProject\Geely\FE-3HP\ATC\01_Application\02_Sources\01_CC\01_APP\EED*/
/****************************************************************************/
 
#define   TOTAL_GROUP_USING              (8)
#define   EXT_GROUP_USING                (1)
#define   EED_u8EEP_Group_Info           (EED_stLayout.stGROUP1.stSystem_EXT.u8EEP_Group_Info)
#define   EED_u8EEP_Version_Major        (EED_stLayout.stGROUP1.stSystem_EXT.u8EEP_Version_Major)
#define   EED_u8EEP_Version_Minor        (EED_stLayout.stGROUP1.stSystem_EXT.u8EEP_Version_Minor)
#define   EED_u8SW_Version_Major         (EED_stLayout.stGROUP1.stSystem_EXT.u8SW_Version_Major)
#define   EED_u8SW_Version_Minor         (EED_stLayout.stGROUP1.stSystem_EXT.u8SW_Version_Minor)
#define   EED_u8DevelopModeMsgEn         (EED_stLayout.stGROUP1.stSystem_EXT.u8DevelopModeMsgEn)
#define   EED_u8DevelopModeStstEn        (EED_stLayout.stGROUP1.stSystem_EXT.u8DevelopModeStstEn)
#define   EED_u8FillerByte_System_Ext1   (EED_stLayout.stGROUP1.stSystem_EXT.u8FillerByte_System_Ext1)
#define   EED_nMMIBuffer_Tbl_Len         (62U)
#define   EED_au8MMIBuffer_Tbl           (EED_stLayout.stGROUP2.stMMI.au8MMIBuffer_Tbl)
#define   EED_nOATBuffer_Tbl_Len         (62U)
#define   EED_au8OATBuffer_Tbl           (EED_stLayout.stGROUP3.stOAT.au8OATBuffer_Tbl)
#define   EED_nDIAGBuffer_Tbl_Len        (254U)
#define   EED_au8DIAGBuffer_Tbl          (EED_stLayout.stGROUP4.stDIAG.au8DIAGBuffer_Tbl)
#define   EED_nDTCBuffer_Tbl_Len         (702U)
#define   EED_au8DTCBuffer_Tbl           (EED_stLayout.stGROUP5.stDTC.au8DTCBuffer_Tbl)
#define   EED_nPTSBuffer_Tbl_Len         (62U)
#define   EED_au8PTSBuffer_Tbl           (EED_stLayout.stGROUP6.stPTS.au8PTSBuffer_Tbl)
#define   EED_nFPBuffer_Tbl_Len          (2U)
#define   EED_au8FPBuffer_Tbl            (EED_stLayout.stGROUP7.stFP.au8FPBuffer_Tbl)
#define   EED_bSystem_SeatHeatersModule  (EED_stLayout.stGROUP8.stSystem.bi8System_BitDefine_Byte_1.SeatHeatersModule)  /* 1 Bits */
#define   EED_bSystem_TemperatureUnit    (EED_stLayout.stGROUP8.stSystem.bi8System_BitDefine_Byte_1.TemperatureUnit)  /* 1 Bits */
#define   EED_bSystem_DefrostForcesBlowertoMax (EED_stLayout.stGROUP8.stSystem.bi8System_BitDefine_Byte_1.DefrostForcesBlowertoMax)  /* 1 Bits */
#define   EED_bSystem_MixedAirDisModeSafety (EED_stLayout.stGROUP8.stSystem.bi8System_BitDefine_Byte_1.MixedAirDisModeSafety)  /* 1 Bits */
#define   EED_bSystem_MixedAirAdaptiveControl (EED_stLayout.stGROUP8.stSystem.bi8System_BitDefine_Byte_1.MixedAirAdaptiveControl)  /* 1 Bits */
#define   EED_bSystem_CompressorControlMode (EED_stLayout.stGROUP8.stSystem.bi8System_BitDefine_Byte_1.CompressorControlMode)  /* 1 Bits */
#define   EED_bSystem_DriverSide         (EED_stLayout.stGROUP8.stSystem.bi8System_BitDefine_Byte_1.DriverSide)  /* 1 Bits */
#define   EED_bi8System_BitDefine_Byte_1 (EED_stLayout.stGROUP8.stSystem.bi8System_BitDefine_Byte_1)  /* Bit 6: SeatHeatersModule [ 1 Bits]  Bit 5: TemperatureUnit [ 1 Bits]  Bit 4: DefrostForcesBlowertoMax [ 1 Bits]  Bit 3: MixedAirDisModeSafety [ 1 Bits]  Bit 2: MixedAirAdaptiveControl [ 1 Bits]  Bit 1: CompressorControlMode [ 1 Bits]  Bit 0: DriverSide [ 1 Bits]   */
#define   EED_u8FillerByte_System1       (EED_stLayout.stGROUP8.stSystem.u8FillerByte_System1)
 
/********************* USER DEFINE MACROS ***************************/
