/********************* MODULE STRUCTURE DEFINITIONS *************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 18/12/2014  14:16:33                                     */
/**           By : test                                                     */
/**        Using : Rdc_Cfg_Template_Release_A01.xls                         */
/**         From : D:\HVACProject\New Development Model\NDM CODE\RDC        */
/**               (D = )                                                    */
/****************************************************************************/
/*****************************************************************************
* FILE DECLARATION
******************************************************************************/
#ifndef RDC_CFG_H
#define RDC_CFG_H
/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
******************************************************************************/
/* System-headerfiles */
#include "General.h"


/*****************************************************************************
* MACROS and STRUCT
*
* In this section declare
* - all macros and structs used in the configuration head file and C file.
******************************************************************************/



/*************************** Define Structures Arrary length ************************/

typedef const struct RDC_stRdcInfo
{
   const uint8    u8VariableConst;
   const uint8    u8ModuleID;
   const uint16   u16ModuleLen;
} RDC_tstRdcInfo;

/*************************** Group Structures ************************/
typedef const struct RDC_stGroupRDC
{
   RDC_tstRdcInfo  stRdcInfo;
   const uint8  u8AddChkSum;
   const uint8  u8XorChkSum;
} RDC_tstGroupRDC;

/********************** LAYOUT STRUCTURE ****************************/
typedef const struct 
{
   RDC_tstGroupRDC  stGroupRDC;
} RDC_tstLayout;

extern const RDC_tstLayout RDC_stRomLayout;
/********************* VARIABLE ACCESS MACROS ***************************/
#define   RDC_u8VariableConst                     (RDC_stRomLayout.stGroupRDC.stRdcInfo.u8VariableConst)
#define   RDC_u8ModuleID                          (RDC_stRomLayout.stGroupRDC.stRdcInfo.u8ModuleID)
#define   RDC_u16ModuleLen                        (RDC_stRomLayout.stGroupRDC.stRdcInfo.u16ModuleLen)

/******************************** END *************************************/
 /*****************************************************************************
* End of check if informations are already included
******************************************************************************/
#endif                                  /* ifndef */

/*****************************************************************************
*RDC_Cfg.h
******************************************************************************/
