/************************** DEFAULTS ************************************/
/********************** Automatically Generated File ************************/
/********************* Do not edit this file manually! **********************/
/** Generated On : 18/12/2014  14:16:34                                     */
/**           By : test                                                     */
/**        Using : Rdc_Cfg_Template_Release_A01.xls                         */
/**         From : D:\HVACProject\New Development Model\NDM CODE\RDC        */
/**               (D = )                                                    */
/****************************************************************************/

/*****************************************************************************
* FILE DECLARATION
*****************************************************************************/

#define RDC_CFG

/*****************************************************************************
* HEADER-FILES (Only those that are needed in this file)
*****************************************************************************/
#include "RDC.h"


/*****************************************************************************
* MODULE GLOBAL CONFIGURATION CONSTANTS
*
* In this section define
* - constants and macros to configure your module. These constants are unknown for other
*   modules
*****************************************************************************/


const RDC_tstLayout RDC_stRomLayout = {

   {  /*----------------------- GroupRDC ---------------------------------------*/

      {  /* RdcInfo */
         0xFF,                                                    /* u8VariableConst */
         0x17,                                                    /* u8ModuleID */
         0x0008,                                                  /* u16ModuleLen */
      },
      0xE1,                                                       /* u8AddChkSum */
      0xE1                                                        /* u8XorChkSum */
   }
};
